package com.burst.sdk.struct.hw;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class META_LINE_S extends Structure {
	/**
	 * \u8d77\u59cb\u70b9<br>
	 * C type : META_POINT_S
	 */
	public META_POINT_S stStartPoint;
	/**
	 * \u7ec8\u6b62\u70b9<br>
	 * C type : META_POINT_S
	 */
	public META_POINT_S stEndPoint;
	public META_LINE_S() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("stStartPoint", "stEndPoint");
	}
	/**
	 * @param stStartPoint \u8d77\u59cb\u70b9<br>
	 * C type : META_POINT_S<br>
	 * @param stEndPoint \u7ec8\u6b62\u70b9<br>
	 * C type : META_POINT_S
	 */
	public META_LINE_S(META_POINT_S stStartPoint, META_POINT_S stEndPoint) {
		super();
		this.stStartPoint = stStartPoint;
		this.stEndPoint = stEndPoint;
	}
	public META_LINE_S(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends META_LINE_S implements Structure.ByReference {
		
	};
	public static class ByValue extends META_LINE_S implements Structure.ByValue {
		
	};
}
