package com.burst.sdk.struct.hw;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_AUTO_DIALING_PLAN extends Structure {
	/** C type : PU_DIALING_PLAN_DAY_S[(7)] */
	public PU_DIALING_PLAN_DAY[] szDalingPlan = new PU_DIALING_PLAN_DAY[7];
	public PU_AUTO_DIALING_PLAN() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("szDalingPlan");
	}
	/** @param szDalingPlan C type : PU_DIALING_PLAN_DAY_S[(7)] */
	public PU_AUTO_DIALING_PLAN(PU_DIALING_PLAN_DAY szDalingPlan[]) {
		super();
		if ((szDalingPlan.length != this.szDalingPlan.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szDalingPlan = szDalingPlan;
	}
	public PU_AUTO_DIALING_PLAN(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_AUTO_DIALING_PLAN implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_AUTO_DIALING_PLAN implements Structure.ByValue {
		
	};
}
