package com.burst.sdk.struct.hw;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_ALARM_REC_INQ_RSP extends Structure {
	/** \u544a\u8b66\u5f55\u50cf\u603b\u6570 */
	public NativeLong ulTotalNum;
	/** \u8d77\u59cb\u7d22\u5f15 */
	public NativeLong ulBeginIndex;
	/** \u7ed3\u675f\u7d22\u5f15 */
	public NativeLong ulEndIndex;
	/**
	 * \u544a\u8b66\u5f55\u50cf\u4fe1\u606f\u5217\u8868<br>
	 * C type : PU_ALARM_REC_INFO_S[5]
	 */
	public PU_ALARM_REC_INFO[] astAlarmRecInfoList = new PU_ALARM_REC_INFO[5];
	/** C type : CHAR[32] */
	public byte[] szReserved = new byte[32];
	public PU_ALARM_REC_INQ_RSP() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ulTotalNum", "ulBeginIndex", "ulEndIndex", "astAlarmRecInfoList", "szReserved");
	}
	/**
	 * @param ulTotalNum \u544a\u8b66\u5f55\u50cf\u603b\u6570<br>
	 * @param ulBeginIndex \u8d77\u59cb\u7d22\u5f15<br>
	 * @param ulEndIndex \u7ed3\u675f\u7d22\u5f15<br>
	 * @param astAlarmRecInfoList \u544a\u8b66\u5f55\u50cf\u4fe1\u606f\u5217\u8868<br>
	 * C type : PU_ALARM_REC_INFO_S[5]<br>
	 * @param szReserved C type : CHAR[32]
	 */
	public PU_ALARM_REC_INQ_RSP(NativeLong ulTotalNum, NativeLong ulBeginIndex, NativeLong ulEndIndex, PU_ALARM_REC_INFO astAlarmRecInfoList[], byte szReserved[]) {
		super();
		this.ulTotalNum = ulTotalNum;
		this.ulBeginIndex = ulBeginIndex;
		this.ulEndIndex = ulEndIndex;
		if ((astAlarmRecInfoList.length != this.astAlarmRecInfoList.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.astAlarmRecInfoList = astAlarmRecInfoList;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public PU_ALARM_REC_INQ_RSP(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_ALARM_REC_INQ_RSP implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_ALARM_REC_INQ_RSP implements Structure.ByValue {
		
	};
}
