package com.burst.sdk.struct.hw;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_ALARM_TIME_PARA_LIST extends Structure {
	/** \u5e03\u9632\u65f6\u95f4\u6bb5\u4e2a\u6570 */
	public NativeLong ulNum;
	/**
	 * \u5e03\u9632\u65f6\u95f4\u6bb5\u6570\u7ec4<br>
	 * C type : PU_ALARM_TIME_S[8]
	 */
	public PU_ALARM_TIME[] stAlarmTime = new PU_ALARM_TIME[8];
	public PU_ALARM_TIME_PARA_LIST() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ulNum", "stAlarmTime");
	}
	/**
	 * @param ulNum \u5e03\u9632\u65f6\u95f4\u6bb5\u4e2a\u6570<br>
	 * @param stAlarmTime \u5e03\u9632\u65f6\u95f4\u6bb5\u6570\u7ec4<br>
	 * C type : PU_ALARM_TIME_S[8]
	 */
	public PU_ALARM_TIME_PARA_LIST(NativeLong ulNum, PU_ALARM_TIME stAlarmTime[]) {
		super();
		this.ulNum = ulNum;
		if ((stAlarmTime.length != this.stAlarmTime.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.stAlarmTime = stAlarmTime;
	}
	public PU_ALARM_TIME_PARA_LIST(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_ALARM_TIME_PARA_LIST implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_ALARM_TIME_PARA_LIST implements Structure.ByValue {
		
	};
}
