package com.burst.sdk.struct.hw;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_ALARM_TIME extends Structure {
	/** \u5faa\u73af\u65b9\u5f0f\uff0c0\uff1a\u4e0d\u5faa\u73af\uff1b1\uff1a\u6bcf\u5468\u5faa\u73af\uff1b */
	public NativeLong ulCycleType;
	/** 0\uff1a\u6bcf\u5929\uff0c1-7\uff1a\u793c\u62dc\u4e00\u81f3\u793c\u62dc\u5929 */
	public NativeLong ulPeriod;
	/**
	 * \u8d77\u59cb\u65f6\u95f4<br>
	 * C type : PU_TIME_S
	 */
	public PU_TIME stStart;
	/**
	 * \u7ed3\u675f\u65f6\u95f4<br>
	 * C type : PU_TIME_S
	 */
	public PU_TIME stEnd;
	public PU_ALARM_TIME() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ulCycleType", "ulPeriod", "stStart", "stEnd");
	}
	/**
	 * @param ulCycleType \u5faa\u73af\u65b9\u5f0f\uff0c0\uff1a\u4e0d\u5faa\u73af\uff1b1\uff1a\u6bcf\u5468\u5faa\u73af\uff1b<br>
	 * @param ulPeriod 0\uff1a\u6bcf\u5929\uff0c1-7\uff1a\u793c\u62dc\u4e00\u81f3\u793c\u62dc\u5929<br>
	 * @param stStart \u8d77\u59cb\u65f6\u95f4<br>
	 * C type : PU_TIME_S<br>
	 * @param stEnd \u7ed3\u675f\u65f6\u95f4<br>
	 * C type : PU_TIME_S
	 */
	public PU_ALARM_TIME(NativeLong ulCycleType, NativeLong ulPeriod, PU_TIME stStart, PU_TIME stEnd) {
		super();
		this.ulCycleType = ulCycleType;
		this.ulPeriod = ulPeriod;
		this.stStart = stStart;
		this.stEnd = stEnd;
	}
	public PU_ALARM_TIME(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_ALARM_TIME implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_ALARM_TIME implements Structure.ByValue {
		
	};
}
