package com.burst.sdk.struct.hw;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_ALARM_LINK_PRIORITY_PARA extends Structure {
	/** \u901a\u9053\u53f7 */
	public NativeLong ulChannelId;
	/**
	 * @see PU_ALARM_LINK_PTZ_PRIORITY<br>
	 * \u4f18\u5148\u7ea7<br>
	 * C type : PU_ALARM_LINK_PTZ_PRIORITY
	 */
	public int enAlarmPriority;
	/** C type : CHAR[32] */
	public byte[] szReserved = new byte[32];
	public PU_ALARM_LINK_PRIORITY_PARA() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ulChannelId", "enAlarmPriority", "szReserved");
	}
	/**
	 * @param ulChannelId \u901a\u9053\u53f7<br>
	 * @param enAlarmPriority @see PU_ALARM_LINK_PTZ_PRIORITY<br>
	 * \u4f18\u5148\u7ea7<br>
	 * C type : PU_ALARM_LINK_PTZ_PRIORITY<br>
	 * @param szReserved C type : CHAR[32]
	 */
	public PU_ALARM_LINK_PRIORITY_PARA(NativeLong ulChannelId, int enAlarmPriority, byte szReserved[]) {
		super();
		this.ulChannelId = ulChannelId;
		this.enAlarmPriority = enAlarmPriority;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public PU_ALARM_LINK_PRIORITY_PARA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_ALARM_LINK_PRIORITY_PARA implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_ALARM_LINK_PRIORITY_PARA implements Structure.ByValue {
		
	};
}
