package com.burst.sdk.struct.hw;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_CMOS_SIZE_PARA extends Structure {
	public NativeLong ulChnID;
	public NativeLong ulIntHorSize;
	public NativeLong ulDotHorSize;
	public NativeLong ulIntVerSize;
	public NativeLong ulDotVerSize;
	/** C type : CHAR[32] */
	public byte[] szReserved = new byte[32];
	public PU_CMOS_SIZE_PARA() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ulChnID", "ulIntHorSize", "ulDotHorSize", "ulIntVerSize", "ulDotVerSize", "szReserved");
	}
	/** @param szReserved C type : CHAR[32] */
	public PU_CMOS_SIZE_PARA(NativeLong ulChnID, NativeLong ulIntHorSize, NativeLong ulDotHorSize, NativeLong ulIntVerSize, NativeLong ulDotVerSize, byte szReserved[]) {
		super();
		this.ulChnID = ulChnID;
		this.ulIntHorSize = ulIntHorSize;
		this.ulDotHorSize = ulDotHorSize;
		this.ulIntVerSize = ulIntVerSize;
		this.ulDotVerSize = ulDotVerSize;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public PU_CMOS_SIZE_PARA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_CMOS_SIZE_PARA implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_CMOS_SIZE_PARA implements Structure.ByValue {
		
	};
}
