package com.burst.sdk.struct.hw;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_DEC_PORT_ABILITY extends Structure {
	/**
	 * 1\2\4\9\16 mode,0 the end<br>
	 * C type : CHAR[16]
	 */
	public byte[] szOutPutModes = new byte[16];
	/** 0:Audio, 1:Video 2:both */
	public NativeLong ulPortType;
	/** \u7aef\u53e3\u662f\u5426\u652f\u6301\u653e\u5927\u663e\u793a */
	public boolean bSupportEnlarge;
	public PU_DEC_PORT_ABILITY() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("szOutPutModes", "ulPortType", "bSupportEnlarge");
	}
	/**
	 * @param szOutPutModes 1\2\4\9\16 mode,0 the end<br>
	 * C type : CHAR[16]<br>
	 * @param ulPortType 0:Audio, 1:Video 2:both<br>
	 * @param bSupportEnlarge \u7aef\u53e3\u662f\u5426\u652f\u6301\u653e\u5927\u663e\u793a
	 */
	public PU_DEC_PORT_ABILITY(byte szOutPutModes[], NativeLong ulPortType, boolean bSupportEnlarge) {
		super();
		if ((szOutPutModes.length != this.szOutPutModes.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szOutPutModes = szOutPutModes;
		this.ulPortType = ulPortType;
		this.bSupportEnlarge = bSupportEnlarge;
	}
	public PU_DEC_PORT_ABILITY(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_DEC_PORT_ABILITY implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_DEC_PORT_ABILITY implements Structure.ByValue {
		
	};
}
