package com.burst.sdk.struct.hw;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_DEC_CHANNEL_INFO extends Structure {
	/** \u901a\u9053ID\u53f7 */
	public NativeLong ulChannelId;
	/** \u964d\u566a\u4f7f\u80fd */
	public boolean bDenoiseFlag;
	/** \u53bb\u96fe\u4f7f\u80fd */
	public boolean bDemistFlag;
	/** \u56fe\u50cf\u653e\u5927\u72b6\u6001 */
	public boolean bEnlargeStatus;
	/**
	 * OSD\u6587\u5b57\u4fe1\u606f<br>
	 * C type : PU_DEC_OSD_STRING_INFO_S
	 */
	public PU_DEC_OSD_STRING_INFO stOsdTextInfo;
	public PU_DEC_CHANNEL_INFO() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ulChannelId", "bDenoiseFlag", "bDemistFlag", "bEnlargeStatus", "stOsdTextInfo");
	}
	/**
	 * @param ulChannelId \u901a\u9053ID\u53f7<br>
	 * @param bDenoiseFlag \u964d\u566a\u4f7f\u80fd<br>
	 * @param bDemistFlag \u53bb\u96fe\u4f7f\u80fd<br>
	 * @param bEnlargeStatus \u56fe\u50cf\u653e\u5927\u72b6\u6001<br>
	 * @param stOsdTextInfo OSD\u6587\u5b57\u4fe1\u606f<br>
	 * C type : PU_DEC_OSD_STRING_INFO_S
	 */
	public PU_DEC_CHANNEL_INFO(NativeLong ulChannelId, boolean bDenoiseFlag, boolean bDemistFlag, boolean bEnlargeStatus, PU_DEC_OSD_STRING_INFO stOsdTextInfo) {
		super();
		this.ulChannelId = ulChannelId;
		this.bDenoiseFlag = bDenoiseFlag;
		this.bDemistFlag = bDemistFlag;
		this.bEnlargeStatus = bEnlargeStatus;
		this.stOsdTextInfo = stOsdTextInfo;
	}
	public PU_DEC_CHANNEL_INFO(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_DEC_CHANNEL_INFO implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_DEC_CHANNEL_INFO implements Structure.ByValue {
		
	};
}
