package com.burst.sdk.struct.hw;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_DECODER_CHANNEL_INFO extends Structure {
	/** \u89e3\u7801\u5668\u901a\u9053\u53f7 */
	public NativeLong ulChannelID;
	/**
	 * \u89e3\u7801\u5668\u901a\u9053\u540d\u79f0<br>
	 * C type : char[32 + 1]
	 */
	public byte[] szChannelName = new byte[32 + 1];
	public PU_DECODER_CHANNEL_INFO() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ulChannelID", "szChannelName");
	}
	/**
	 * @param ulChannelID \u89e3\u7801\u5668\u901a\u9053\u53f7<br>
	 * @param szChannelName \u89e3\u7801\u5668\u901a\u9053\u540d\u79f0<br>
	 * C type : char[32 + 1]
	 */
	public PU_DECODER_CHANNEL_INFO(NativeLong ulChannelID, byte szChannelName[]) {
		super();
		this.ulChannelID = ulChannelID;
		if ((szChannelName.length != this.szChannelName.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szChannelName = szChannelName;
	}
	public PU_DECODER_CHANNEL_INFO(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_DECODER_CHANNEL_INFO implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_DECODER_CHANNEL_INFO implements Structure.ByValue {
		
	};
}
