package com.burst.sdk.struct.hw;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_DENOISE_PARA extends Structure {
	/**
	 * \u6a21\u5f0f\u5f00\u5173<br>
	 * C type : PU_DENOISE_MODE_E
	 */
	public int enDenoiseMode;
	/** \u8303\u56f4\uff0c\u7d22\u5c3c1~5 \u65e5\u7acb1~3 */
	public NativeLong lNRLevel;
	/** \u65f6\u57df\u964d\u566a */
	public NativeLong ulTfcLevel;
	/** \u7a7a\u57df\u964d\u566a */
	public NativeLong ulSfcLevel;
	public PU_DENOISE_PARA() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("enDenoiseMode", "lNRLevel", "ulTfcLevel", "ulSfcLevel");
	}
	/**
	 * @param enDenoiseMode \u6a21\u5f0f\u5f00\u5173<br>
	 * C type : PU_DENOISE_MODE_E<br>
	 * @param lNRLevel \u8303\u56f4\uff0c\u7d22\u5c3c1~5 \u65e5\u7acb1~3<br>
	 * @param ulTfcLevel \u65f6\u57df\u964d\u566a<br>
	 * @param ulSfcLevel \u7a7a\u57df\u964d\u566a
	 */
	public PU_DENOISE_PARA(int enDenoiseMode, NativeLong lNRLevel, NativeLong ulTfcLevel, NativeLong ulSfcLevel) {
		super();
		this.enDenoiseMode = enDenoiseMode;
		this.lNRLevel = lNRLevel;
		this.ulTfcLevel = ulTfcLevel;
		this.ulSfcLevel = ulSfcLevel;
	}
	public PU_DENOISE_PARA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_DENOISE_PARA implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_DENOISE_PARA implements Structure.ByValue {
		
	};
}
