package com.burst.sdk.struct.hw;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_FACE_DETC_DL_PARA extends Structure {
	/** \u4f7f\u80fd */
	public boolean bEnable;
	/** \u544a\u8b66\u68c0\u6d4b\u65f6\u95f4 */
	public NativeLong ulAlarmTime;
	/** \u68c0\u6d4b\u7075\u654f\u5ea6 */
	public NativeLong ulSensitivity;
	/** \u4eba\u8138\u68c0\u6d4b\u7075\u654f\u5ea6\uff0c\u9884\u7559 */
	public NativeLong ulFaceSensitivity;
	/** \u4eba\u4f53\u68c0\u6d4b\u7075\u654f\u5ea6\uff0c\u9884\u7559 */
	public NativeLong ulBodySensitivity;
	/** \u4eba\u8138\u8d28\u91cf\u8fc7\u6ee4\u7075\u654f\u5ea6\uff0c\u9884\u7559 */
	public NativeLong ulFaceKpsSensitivity;
	/** \u4eba\u4f53\u8d28\u91cf\u8fc7\u6ee4\u7075\u654f\u5ea6\uff0c\u9884\u7559 */
	public NativeLong ulBodyKpsSensitivity;
	/** \u6700\u5c0f\u4eba\u8138 */
	public NativeLong ulMinPupilDist;
	/** \u6700\u5927\u4eba\u8138 */
	public NativeLong ulMaxPupilDist;
	/**
	 * \u68c0\u6d4b\u6a21\u5f0f<br>
	 * C type : PU_FACE_DETECTION_DL_MODE_E
	 */
	public int enMode;
	/** \u4eba\u8138\u66dd\u5149 */
	public boolean bFaceExposure;
	/** \u4eba\u8138\u66dd\u5149\u7075\u654f\u5ea6 */
	public NativeLong ulROIMeterLevel;
	/** C type : CHAR[32] */
	public byte[] szReserved = new byte[32];
	public PU_FACE_DETC_DL_PARA() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("bEnable", "ulAlarmTime", "ulSensitivity", "ulFaceSensitivity", "ulBodySensitivity", "ulFaceKpsSensitivity", "ulBodyKpsSensitivity", "ulMinPupilDist", "ulMaxPupilDist", "enMode", "bFaceExposure", "ulROIMeterLevel", "szReserved");
	}
	public PU_FACE_DETC_DL_PARA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_FACE_DETC_DL_PARA implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_FACE_DETC_DL_PARA implements Structure.ByValue {
		
	};
}
