package com.burst.sdk.struct.hw;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_FEC_PARA extends Structure {
	public NativeLong ulChannelId;
	/** \u524d\u5411\u7ea0\u9519\u4f7f\u80fd */
	public boolean bEnable;
	/**
	 * \u524d\u5411\u7ea0\u9519\u4e22\u5305\u7387<br>
	 * C type : PU_FEC_PACKET_LOSS_RATIO_E
	 */
	public int enPacketLossRatio;
	/** C type : CHAR[32] */
	public byte[] szReserved = new byte[32];
	public PU_FEC_PARA() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ulChannelId", "bEnable", "enPacketLossRatio", "szReserved");
	}
	/**
	 * @param bEnable \u524d\u5411\u7ea0\u9519\u4f7f\u80fd<br>
	 * @param enPacketLossRatio \u524d\u5411\u7ea0\u9519\u4e22\u5305\u7387<br>
	 * C type : PU_FEC_PACKET_LOSS_RATIO_E<br>
	 * @param szReserved C type : CHAR[32]
	 */
	public PU_FEC_PARA(NativeLong ulChannelId, boolean bEnable, int enPacketLossRatio, byte szReserved[]) {
		super();
		this.ulChannelId = ulChannelId;
		this.bEnable = bEnable;
		this.enPacketLossRatio = enPacketLossRatio;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public PU_FEC_PARA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_FEC_PARA implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_FEC_PARA implements Structure.ByValue {
		
	};
}
