package com.burst.sdk.struct.hw;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_HARD_DISK_PARA extends Structure {
	/** C type : CHAR[12] */
	public byte[] szDiskFac = new byte[12];
	/** C type : PU_DISK_TYPE_E */
	public int enDiskType;
	public NativeLong ulAllSpace;
	public NativeLong ulLeftSpace;
	/** C type : CHAR[32] */
	public byte[] szReserved = new byte[32];
	public PU_HARD_DISK_PARA() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("szDiskFac", "enDiskType", "ulAllSpace", "ulLeftSpace", "szReserved");
	}
	/**
	 * @param szDiskFac C type : CHAR[12]<br>
	 * @param enDiskType C type : PU_DISK_TYPE_E<br>
	 * @param szReserved C type : CHAR[32]
	 */
	public PU_HARD_DISK_PARA(byte szDiskFac[], int enDiskType, NativeLong ulAllSpace, NativeLong ulLeftSpace, byte szReserved[]) {
		super();
		if ((szDiskFac.length != this.szDiskFac.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szDiskFac = szDiskFac;
		this.enDiskType = enDiskType;
		this.ulAllSpace = ulAllSpace;
		this.ulLeftSpace = ulLeftSpace;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public PU_HARD_DISK_PARA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_HARD_DISK_PARA implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_HARD_DISK_PARA implements Structure.ByValue {
		
	};
}
