package com.burst.sdk.struct.hw;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_ITS_MANUAL_SNAPSHOT_PARA extends Structure {
	/** \u6293\u62cd\u5f20\u6570,\u6700\u5927\u503cMAX_BURST_SHOOTING_NUM  (\u76ee\u524d\u53ea\u652f\u63011,\u5176\u4ed6\u503c\u65e0\u6548) */
	public NativeLong ulSnapNum;
	/**
	 * \u6293\u62cd\u95f4\u9694(ms) \u8303\u56f4[MIN_ITS_SNAPSHOT_INTERVAL, MAX_ITS_SNAPSHOT_INTERVAL]<br>
	 * C type : ULONG[5 - 1]
	 */
	public NativeLong[] aulSnapInterval = new NativeLong[5 - 1];
	/** C type : CHAR[32] */
	public byte[] szReserved = new byte[32];
	public PU_ITS_MANUAL_SNAPSHOT_PARA() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ulSnapNum", "aulSnapInterval", "szReserved");
	}
	/**
	 * @param ulSnapNum \u6293\u62cd\u5f20\u6570,\u6700\u5927\u503cMAX_BURST_SHOOTING_NUM  (\u76ee\u524d\u53ea\u652f\u63011,\u5176\u4ed6\u503c\u65e0\u6548)<br>
	 * @param aulSnapInterval \u6293\u62cd\u95f4\u9694(ms) \u8303\u56f4[MIN_ITS_SNAPSHOT_INTERVAL, MAX_ITS_SNAPSHOT_INTERVAL]<br>
	 * C type : ULONG[5 - 1]<br>
	 * @param szReserved C type : CHAR[32]
	 */
	public PU_ITS_MANUAL_SNAPSHOT_PARA(NativeLong ulSnapNum, NativeLong aulSnapInterval[], byte szReserved[]) {
		super();
		this.ulSnapNum = ulSnapNum;
		if ((aulSnapInterval.length != this.aulSnapInterval.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.aulSnapInterval = aulSnapInterval;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public PU_ITS_MANUAL_SNAPSHOT_PARA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_ITS_MANUAL_SNAPSHOT_PARA implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_ITS_MANUAL_SNAPSHOT_PARA implements Structure.ByValue {
		
	};
}
