package com.burst.sdk.struct.hw;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_IGT_AEREDTC_ALARM_PARA extends Structure {
	public NativeLong ulChannelId;
	public boolean bEnable;
	/** \u544a\u8b66\u68c0\u6d4b\u95f4\u9694 */
	public NativeLong ulAlarmInterval;
	/**
	 * \u76ee\u6807\u8bc6\u522b\u6a21\u5f0f<br>
	 * C type : PU_IGT_TARGET_MODE_E
	 */
	public int enTargetDetecMode;
	/** \u505c\u7559\u65f6\u95f4 */
	public NativeLong ulRemainTime;
	/**
	 * \u533a\u57df\u6570\u7ec4\uff1a\u83b7\u53d6\u65f6\u4f1a\u8fd4\u56de\u6240\u6709\u533a\u57df\u4fe1\u606f\uff0c\u5982\u679c\u533a\u57df\u5750\u6807\u4e3a0\u8bf4\u660e\u4e0d\u518d\u5f53\u524d\u955c\u5934\u8303\u56f4\u5185(\u4f1a\u8fd4\u56de\u7d22\u5f15)<br>
	 * C type : PU_IGT_AERADTC_LIST_S
	 */
	public PU_IGT_AERADTC_LIST stAreaDtcList;
	/**
	 * \u5e03\u9632\u8ba1\u5212<br>
	 * C type : PU_ALARM_TIME_LIST_S
	 */
	public PU_ALARM_TIME_PARA_LIST stAreaGuardPlan;
	/** C type : CHAR[32] */
	public byte[] szReserved = new byte[32];
	public PU_IGT_AEREDTC_ALARM_PARA() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ulChannelId", "bEnable", "ulAlarmInterval", "enTargetDetecMode", "ulRemainTime", "stAreaDtcList", "stAreaGuardPlan", "szReserved");
	}
	/**
	 * @param ulAlarmInterval \u544a\u8b66\u68c0\u6d4b\u95f4\u9694<br>
	 * @param enTargetDetecMode \u76ee\u6807\u8bc6\u522b\u6a21\u5f0f<br>
	 * C type : PU_IGT_TARGET_MODE_E<br>
	 * @param ulRemainTime \u505c\u7559\u65f6\u95f4<br>
	 * @param stAreaDtcList \u533a\u57df\u6570\u7ec4\uff1a\u83b7\u53d6\u65f6\u4f1a\u8fd4\u56de\u6240\u6709\u533a\u57df\u4fe1\u606f\uff0c\u5982\u679c\u533a\u57df\u5750\u6807\u4e3a0\u8bf4\u660e\u4e0d\u518d\u5f53\u524d\u955c\u5934\u8303\u56f4\u5185(\u4f1a\u8fd4\u56de\u7d22\u5f15)<br>
	 * C type : PU_IGT_AERADTC_LIST_S<br>
	 * @param stAreaGuardPlan \u5e03\u9632\u8ba1\u5212<br>
	 * C type : PU_ALARM_TIME_LIST_S<br>
	 * @param szReserved C type : CHAR[32]
	 */
	public PU_IGT_AEREDTC_ALARM_PARA(NativeLong ulChannelId, boolean bEnable, NativeLong ulAlarmInterval, int enTargetDetecMode, NativeLong ulRemainTime, PU_IGT_AERADTC_LIST stAreaDtcList, PU_ALARM_TIME_PARA_LIST stAreaGuardPlan, byte szReserved[]) {
		super();
		this.ulChannelId = ulChannelId;
		this.bEnable = bEnable;
		this.ulAlarmInterval = ulAlarmInterval;
		this.enTargetDetecMode = enTargetDetecMode;
		this.ulRemainTime = ulRemainTime;
		this.stAreaDtcList = stAreaDtcList;
		this.stAreaGuardPlan = stAreaGuardPlan;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public PU_IGT_AEREDTC_ALARM_PARA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_IGT_AEREDTC_ALARM_PARA implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_IGT_AEREDTC_ALARM_PARA implements Structure.ByValue {
		
	};
}
