package com.burst.sdk.struct.hw;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_INVADE_ALARM_PARA extends Structure {
	/** \u89c6\u9891\u901a\u9053ID */
	public NativeLong ulChannel;
	/**
	 * \u5165\u4fb5\u68c0\u6d4b\u53c2\u6570<br>
	 * C type : PU_INVADE_PARA_S
	 */
	public PU_INVADE_PARA stInvadePara;
	/**
	 * \u5e03\u9632\u65f6\u95f4\u5217\u8868<br>
	 * C type : PU_ALARM_TIME_LIST_S
	 */
	public PU_ALARM_TIME_PARA_LIST stAlarmTimeList;
	public PU_INVADE_ALARM_PARA() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ulChannel", "stInvadePara", "stAlarmTimeList");
	}
	/**
	 * @param ulChannel \u89c6\u9891\u901a\u9053ID<br>
	 * @param stInvadePara \u5165\u4fb5\u68c0\u6d4b\u53c2\u6570<br>
	 * C type : PU_INVADE_PARA_S<br>
	 * @param stAlarmTimeList \u5e03\u9632\u65f6\u95f4\u5217\u8868<br>
	 * C type : PU_ALARM_TIME_LIST_S
	 */
	public PU_INVADE_ALARM_PARA(NativeLong ulChannel, PU_INVADE_PARA stInvadePara, PU_ALARM_TIME_PARA_LIST stAlarmTimeList) {
		super();
		this.ulChannel = ulChannel;
		this.stInvadePara = stInvadePara;
		this.stAlarmTimeList = stAlarmTimeList;
	}
	public PU_INVADE_ALARM_PARA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_INVADE_ALARM_PARA implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_INVADE_ALARM_PARA implements Structure.ByValue {
		
	};
}
