package com.burst.sdk.struct.hw;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_ITS_FLOW_RATE_PARA extends Structure {
	/**
	 * \u4f7f\u80fd\u5f00\u5173<br>
	 * C type : PU_ENABLE_TYPE_E
	 */
	public int bEnable;
	public NativeLong ulChannelId;
	/** \u8f66\u6d41\u91cf\u7edf\u8ba1\u95f4\u9694 */
	public NativeLong uInterval;
	/** C type : CHAR[32] */
	public byte[] szReserve = new byte[32];
	public PU_ITS_FLOW_RATE_PARA() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("bEnable", "ulChannelId", "uInterval", "szReserve");
	}
	/**
	 * @param bEnable \u4f7f\u80fd\u5f00\u5173<br>
	 * C type : PU_ENABLE_TYPE_E<br>
	 * @param uInterval \u8f66\u6d41\u91cf\u7edf\u8ba1\u95f4\u9694<br>
	 * @param szReserve C type : CHAR[32]
	 */
	public PU_ITS_FLOW_RATE_PARA(int bEnable, NativeLong ulChannelId, NativeLong uInterval, byte szReserve[]) {
		super();
		this.bEnable = bEnable;
		this.ulChannelId = ulChannelId;
		this.uInterval = uInterval;
		if ((szReserve.length != this.szReserve.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserve = szReserve;
	}
	public PU_ITS_FLOW_RATE_PARA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_ITS_FLOW_RATE_PARA implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_ITS_FLOW_RATE_PARA implements Structure.ByValue {
		
	};
}
