package com.burst.sdk.struct.hw;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_ITS_LANE_PARAM_UNIT extends Structure {
	/**
	 * \u57fa\u7840\u8f66\u9053\u4fe1\u606f<br>
	 * C type : PU_ITS_LANE_INFO_BASE_UNIT_S
	 */
	public PU_ITS_LANE_INFO_BASE_UNIT stLaneInfoBaseU;
	/**
	 * \u901f\u5ea6\u9650\u5236\u914d\u7f6e<br>
	 * C type : PU_ITS_SPEED_LIMIT_S
	 */
	public PU_ITS_SPEED_LIMIT stSpeedLimit;
	/** \u8fdd\u7ae0\u5f55\u50cf\u4f7f\u80fd */
	public boolean bRegulationRecord;
	/** \u5916\u7f6e\u706f\u5173\u8054BitMap */
	public int iExterLampBitMap;
	/** C type : CHAR[32] */
	public byte[] szReserve = new byte[32];
	public PU_ITS_LANE_PARAM_UNIT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("stLaneInfoBaseU", "stSpeedLimit", "bRegulationRecord", "iExterLampBitMap", "szReserve");
	}
	/**
	 * @param stLaneInfoBaseU \u57fa\u7840\u8f66\u9053\u4fe1\u606f<br>
	 * C type : PU_ITS_LANE_INFO_BASE_UNIT_S<br>
	 * @param stSpeedLimit \u901f\u5ea6\u9650\u5236\u914d\u7f6e<br>
	 * C type : PU_ITS_SPEED_LIMIT_S<br>
	 * @param bRegulationRecord \u8fdd\u7ae0\u5f55\u50cf\u4f7f\u80fd<br>
	 * @param iExterLampBitMap \u5916\u7f6e\u706f\u5173\u8054BitMap<br>
	 * @param szReserve C type : CHAR[32]
	 */
	public PU_ITS_LANE_PARAM_UNIT(PU_ITS_LANE_INFO_BASE_UNIT stLaneInfoBaseU, PU_ITS_SPEED_LIMIT stSpeedLimit, boolean bRegulationRecord, int iExterLampBitMap, byte szReserve[]) {
		super();
		this.stLaneInfoBaseU = stLaneInfoBaseU;
		this.stSpeedLimit = stSpeedLimit;
		this.bRegulationRecord = bRegulationRecord;
		this.iExterLampBitMap = iExterLampBitMap;
		if ((szReserve.length != this.szReserve.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserve = szReserve;
	}
	public PU_ITS_LANE_PARAM_UNIT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_ITS_LANE_PARAM_UNIT implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_ITS_LANE_PARAM_UNIT implements Structure.ByValue {
		
	};
}
