package com.burst.sdk.struct.hw;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_IPFILTER_RULES_INFO extends Structure {
	/** \u662f\u5426\u542f\u7528IP\u8fc7\u6ee4 */
	public boolean bIpFilterEnable;
	/**
	 * IP\u8fc7\u6ee4\u7b56\u7565:\u767d\u540d\u5355 or \u9ed1\u540d\u5355<br>
	 * C type : PU_IP_FILTER_STRATEGY_E
	 */
	public int enIpFilterStrategy;
	/** IP\u5730\u5740\u89c4\u5219\u6761\u76ee */
	public NativeLong ulIpFilterRulesNum;
	/**
	 * IP\u5730\u5740\u89c4\u5219\u5217\u8868<br>
	 * C type : PU_IPFILTER_RULES_S[3]
	 */
	public PU_IPFILTER_RULES[] stIpFilterRulesList = new PU_IPFILTER_RULES[3];
	/** C type : CHAR[32] */
	public byte[] szReserve = new byte[32];
	public PU_IPFILTER_RULES_INFO() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("bIpFilterEnable", "enIpFilterStrategy", "ulIpFilterRulesNum", "stIpFilterRulesList", "szReserve");
	}
	/**
	 * @param bIpFilterEnable \u662f\u5426\u542f\u7528IP\u8fc7\u6ee4<br>
	 * @param enIpFilterStrategy IP\u8fc7\u6ee4\u7b56\u7565:\u767d\u540d\u5355 or \u9ed1\u540d\u5355<br>
	 * C type : PU_IP_FILTER_STRATEGY_E<br>
	 * @param ulIpFilterRulesNum IP\u5730\u5740\u89c4\u5219\u6761\u76ee<br>
	 * @param stIpFilterRulesList IP\u5730\u5740\u89c4\u5219\u5217\u8868<br>
	 * C type : PU_IPFILTER_RULES_S[3]<br>
	 * @param szReserve C type : CHAR[32]
	 */
	public PU_IPFILTER_RULES_INFO(boolean bIpFilterEnable, int enIpFilterStrategy, NativeLong ulIpFilterRulesNum, PU_IPFILTER_RULES stIpFilterRulesList[], byte szReserve[]) {
		super();
		this.bIpFilterEnable = bIpFilterEnable;
		this.enIpFilterStrategy = enIpFilterStrategy;
		this.ulIpFilterRulesNum = ulIpFilterRulesNum;
		if ((stIpFilterRulesList.length != this.stIpFilterRulesList.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.stIpFilterRulesList = stIpFilterRulesList;
		if ((szReserve.length != this.szReserve.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserve = szReserve;
	}
	public PU_IPFILTER_RULES_INFO(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_IPFILTER_RULES_INFO implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_IPFILTER_RULES_INFO implements Structure.ByValue {
		
	};
}
