package com.burst.sdk.struct.hw;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_MIN_FOCUS_VALUE extends Structure {
	/**
	 * \u6700\u5c0f\u805a\u7126\u8ddd\u79bb<br>
	 * C type : PU_MIN_FOCUS_E
	 */
	public int enMinFocus;
	public PU_MIN_FOCUS_VALUE() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("enMinFocus");
	}
	/**
	 * @param enMinFocus \u6700\u5c0f\u805a\u7126\u8ddd\u79bb<br>
	 * C type : PU_MIN_FOCUS_E
	 */
	public PU_MIN_FOCUS_VALUE(int enMinFocus) {
		super();
		this.enMinFocus = enMinFocus;
	}
	public PU_MIN_FOCUS_VALUE(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_MIN_FOCUS_VALUE implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_MIN_FOCUS_VALUE implements Structure.ByValue {
		
	};
}
