package com.burst.sdk.struct.hw;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_MEDIA_ENC_PARA extends Structure {
	/**
	 * \u52a0\u5bc6\u7c7b\u578b\uff0c\u76ee\u524d\u4ec5\u652f\u6301AES256 CBC\u6a21\u5f0f<br>
	 * C type : PU_MEDIA_CRYPTO_TYPE_E
	 */
	public int enMediaCryptoType;
	/**
	 * \u6307\u5411\u52a0\u5bc6\u7c7b\u578b\u5bf9\u5e94\u7ed3\u6784\u4f53\u7684\u6307\u9488<br>
	 * C type : VOID*
	 */
	public Pointer pstEncPara;
	public PU_MEDIA_ENC_PARA() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("enMediaCryptoType", "pstEncPara");
	}
	/**
	 * @param enMediaCryptoType \u52a0\u5bc6\u7c7b\u578b\uff0c\u76ee\u524d\u4ec5\u652f\u6301AES256 CBC\u6a21\u5f0f<br>
	 * C type : PU_MEDIA_CRYPTO_TYPE_E<br>
	 * @param pstEncPara \u6307\u5411\u52a0\u5bc6\u7c7b\u578b\u5bf9\u5e94\u7ed3\u6784\u4f53\u7684\u6307\u9488<br>
	 * C type : VOID*
	 */
	public PU_MEDIA_ENC_PARA(int enMediaCryptoType, Pointer pstEncPara) {
		super();
		this.enMediaCryptoType = enMediaCryptoType;
		this.pstEncPara = pstEncPara;
	}
	public PU_MEDIA_ENC_PARA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_MEDIA_ENC_PARA implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_MEDIA_ENC_PARA implements Structure.ByValue {
		
	};
}
