package com.burst.sdk.struct.hw;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_OUTOFFOCUS_DETECT_PARA extends Structure {
	/** \u901a\u9053\u53f7 */
	public NativeLong ulChnID;
	/** \u4f7f\u80fd */
	public boolean bEnable;
	/** \u7075\u654f\u5ea6 */
	public NativeLong ulSensitivity;
	/** \u544a\u8b66\u4e0a\u62a5\u95f4\u9694 */
	public NativeLong ulAlarmInterval;
	/**
	 * \u5e03\u9632\u65f6\u95f4\u5217\u8868<br>
	 * C type : PU_ALARM_TIME_LIST_S
	 */
	public PU_ALARM_TIME_PARA_LIST stAlarmTimeList;
	/** C type : CHAR[32] */
	public byte[] szReserved = new byte[32];
	public PU_OUTOFFOCUS_DETECT_PARA() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ulChnID", "bEnable", "ulSensitivity", "ulAlarmInterval", "stAlarmTimeList", "szReserved");
	}
	/**
	 * @param ulChnID \u901a\u9053\u53f7<br>
	 * @param bEnable \u4f7f\u80fd<br>
	 * @param ulSensitivity \u7075\u654f\u5ea6<br>
	 * @param ulAlarmInterval \u544a\u8b66\u4e0a\u62a5\u95f4\u9694<br>
	 * @param stAlarmTimeList \u5e03\u9632\u65f6\u95f4\u5217\u8868<br>
	 * C type : PU_ALARM_TIME_LIST_S<br>
	 * @param szReserved C type : CHAR[32]
	 */
	public PU_OUTOFFOCUS_DETECT_PARA(NativeLong ulChnID, boolean bEnable, NativeLong ulSensitivity, NativeLong ulAlarmInterval, PU_ALARM_TIME_PARA_LIST stAlarmTimeList, byte szReserved[]) {
		super();
		this.ulChnID = ulChnID;
		this.bEnable = bEnable;
		this.ulSensitivity = ulSensitivity;
		this.ulAlarmInterval = ulAlarmInterval;
		this.stAlarmTimeList = stAlarmTimeList;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public PU_OUTOFFOCUS_DETECT_PARA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_OUTOFFOCUS_DETECT_PARA implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_OUTOFFOCUS_DETECT_PARA implements Structure.ByValue {
		
	};
}
