package com.burst.sdk.struct.hw;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_PTZ_PRESET_PARA_EX extends Structure {
	/** \u901a\u9053ID */
	public NativeLong ulChannelId;
	/**
	 * \u9884\u7f6e\u4f4d\u540d\u79f0<br>
	 * C type : CHAR[32]
	 */
	public byte[] szPresetName = new byte[32];
	/** \u9884\u7f6e\u4f4d\u7d22\u5f15 */
	public NativeLong ulIndex;
	/**
	 * \u9884\u7f6e\u4f4d\u547d\u4ee4\u5b57<br>
	 * C type : PU_PTZ_PRESET_CMD_E
	 */
	public int enPresetCmd;
	/** \u9a71\u52a8\u5c42\u805a\u7126\u8bb0\u5fc6\u4f7f\u80fd\u5f00\u5173,0:\u4e0d\u4f7f\u80fd,1:\u4f7f\u80fd */
	public boolean bEnableFocusInfo;
	/**
	 * \u9884\u7559\u5b57<br>
	 * C type : CHAR[32]
	 */
	public byte[] szReserve = new byte[32];
	public PU_PTZ_PRESET_PARA_EX() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ulChannelId", "szPresetName", "ulIndex", "enPresetCmd", "bEnableFocusInfo", "szReserve");
	}
	/**
	 * @param ulChannelId \u901a\u9053ID<br>
	 * @param szPresetName \u9884\u7f6e\u4f4d\u540d\u79f0<br>
	 * C type : CHAR[32]<br>
	 * @param ulIndex \u9884\u7f6e\u4f4d\u7d22\u5f15<br>
	 * @param enPresetCmd \u9884\u7f6e\u4f4d\u547d\u4ee4\u5b57<br>
	 * C type : PU_PTZ_PRESET_CMD_E<br>
	 * @param bEnableFocusInfo \u9a71\u52a8\u5c42\u805a\u7126\u8bb0\u5fc6\u4f7f\u80fd\u5f00\u5173,0:\u4e0d\u4f7f\u80fd,1:\u4f7f\u80fd<br>
	 * @param szReserve \u9884\u7559\u5b57<br>
	 * C type : CHAR[32]
	 */
	public PU_PTZ_PRESET_PARA_EX(NativeLong ulChannelId, byte szPresetName[], NativeLong ulIndex, int enPresetCmd, boolean bEnableFocusInfo, byte szReserve[]) {
		super();
		this.ulChannelId = ulChannelId;
		if ((szPresetName.length != this.szPresetName.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szPresetName = szPresetName;
		this.ulIndex = ulIndex;
		this.enPresetCmd = enPresetCmd;
		this.bEnableFocusInfo = bEnableFocusInfo;
		if ((szReserve.length != this.szReserve.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserve = szReserve;
	}
	public PU_PTZ_PRESET_PARA_EX(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_PTZ_PRESET_PARA_EX implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_PTZ_PRESET_PARA_EX implements Structure.ByValue {
		
	};
}
