package com.burst.sdk.struct.hw;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_POINT extends Structure {
	/** X\u8f74\u5750\u6807(0-352) */
	public short usPosX;
	/** Y\u8f74\u5750\u6807(0-288) */
	public short usPosY;
	public PU_POINT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("usPosX", "usPosY");
	}
	/**
	 * @param usPosX X\u8f74\u5750\u6807(0-352)<br>
	 * @param usPosY Y\u8f74\u5750\u6807(0-288)
	 */
	public PU_POINT(short usPosX, short usPosY) {
		super();
		this.usPosX = usPosX;
		this.usPosY = usPosY;
	}
	public PU_POINT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_POINT implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_POINT implements Structure.ByValue {
		
	};
}
