package com.burst.sdk.struct.hw;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_RESOLUTION_BASIC_PARA extends Structure {
	/** \u662f\u5426\u9ad8\u6e05 */
	public boolean bdevIsHD;
	/**
	 * \u8bbe\u5907\u89c6\u9891\u5206\u8fa8\u7387<br>
	 * C type : PU_RESOLUTION_TYPE_E
	 */
	public int enResolution;
	/** C type : CHAR[32] */
	public byte[] szReserved = new byte[32];
	public PU_RESOLUTION_BASIC_PARA() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("bdevIsHD", "enResolution", "szReserved");
	}
	/**
	 * @param bdevIsHD \u662f\u5426\u9ad8\u6e05<br>
	 * @param enResolution \u8bbe\u5907\u89c6\u9891\u5206\u8fa8\u7387<br>
	 * C type : PU_RESOLUTION_TYPE_E<br>
	 * @param szReserved C type : CHAR[32]
	 */
	public PU_RESOLUTION_BASIC_PARA(boolean bdevIsHD, int enResolution, byte szReserved[]) {
		super();
		this.bdevIsHD = bdevIsHD;
		this.enResolution = enResolution;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public PU_RESOLUTION_BASIC_PARA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_RESOLUTION_BASIC_PARA implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_RESOLUTION_BASIC_PARA implements Structure.ByValue {
		
	};
}
