package com.burst.sdk.struct.hw;
import com.sun.jna.Pointer;
import com.sun.jna.Union;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_SNMP_AUTH_INFO extends Union {
	/**
	 * \u793e\u56e2\u540d\uff0c\u53d1\u9001v1/v2c\u7248\u672c\u7684trap\u4f7f\u7528<br>
	 * C type : CHAR[(16 + 1)]
	 */
	public byte[] szCommunityName = new byte[16 + 1];
	/**
	 * \u7528\u6237\u4fe1\u606f\uff0c\u53d1\u9001v3\u7248\u672c\u7684trap\u4f7f\u7528<br>
	 * C type : PU_SNMPV3_USER_INFO_S
	 */
	public PU_SNMPV3_USER_INFO stUserInfo;
	public PU_SNMP_AUTH_INFO() {
		super();
	}
	/**
	 * @param szCommunityName \u793e\u56e2\u540d\uff0c\u53d1\u9001v1/v2c\u7248\u672c\u7684trap\u4f7f\u7528<br>
	 * C type : CHAR[(16 + 1)]
	 */
	public PU_SNMP_AUTH_INFO(byte szCommunityName[]) {
		super();
		if ((szCommunityName.length != this.szCommunityName.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szCommunityName = szCommunityName;
		setType(byte[].class);
	}
	/**
	 * @param stUserInfo \u7528\u6237\u4fe1\u606f\uff0c\u53d1\u9001v3\u7248\u672c\u7684trap\u4f7f\u7528<br>
	 * C type : PU_SNMPV3_USER_INFO_S
	 */
	public PU_SNMP_AUTH_INFO(PU_SNMPV3_USER_INFO stUserInfo) {
		super();
		this.stUserInfo = stUserInfo;
		setType(PU_SNMPV3_USER_INFO.class);
	}
	public PU_SNMP_AUTH_INFO(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_SNMP_AUTH_INFO implements com.sun.jna.Structure.ByReference {
		
	};
	public static class ByValue extends PU_SNMP_AUTH_INFO implements com.sun.jna.Structure.ByValue {
		
	};
}
