package com.burst.sdk.struct.hw;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_USER_DEFINED_SCAN_PARA extends Structure {
	/** \u82b1\u6837\u626b\u63cf\u8def\u5f84 */
	public NativeLong ulUserDefineIndex;
	public PU_USER_DEFINED_SCAN_PARA() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ulUserDefineIndex");
	}
	/** @param ulUserDefineIndex \u82b1\u6837\u626b\u63cf\u8def\u5f84 */
	public PU_USER_DEFINED_SCAN_PARA(NativeLong ulUserDefineIndex) {
		super();
		this.ulUserDefineIndex = ulUserDefineIndex;
	}
	public PU_USER_DEFINED_SCAN_PARA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_USER_DEFINED_SCAN_PARA implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_USER_DEFINED_SCAN_PARA implements Structure.ByValue {
		
	};
}
