package com.burst.sdk.struct.hw;
import com.burst.sdk.constanst.HWPuSDKEnum;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import  com.burst.sdk.constanst.HWPuSDKEnum;

import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_VIDEO_STREAM_INFO_V2 extends Structure {
	/** \u901a\u9053ID */
	public NativeLong ulChannelId;
	/**
	 * @see PU_STREAM_MODE_E<br>
	 * \u89c6\u9891\u6d41\u7c7b\u578b<br>
	 * C type : PU_STREAM_MODE_E
	 */
	public int enStreamMode;
	/**
	 * \u89c6\u9891\u5c5e\u6027<br>
	 * C type : PU_STREAM_ATTRIBUTE_S[PU_VIEDO_STREAM_FIVE]
	 */
	public PU_STREAM_ATTRIBUTE[] stStreamAttribute = new PU_STREAM_ATTRIBUTE[(int) HWPuSDKEnum.PU_STREAM_MODE_E.PU_VIEDO_STREAM_FIVE];
	/**
	 * szReserve[0]\u6807\u8bc6\u5168\u5e27\u7387  25:25HZ 30:30HZ 50\uff1a50HZ 60:60HZ<br>
	 * C type : CHAR[32]
	 */
	public byte[] szReserved = new byte[32];
	public PU_VIDEO_STREAM_INFO_V2() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ulChannelId", "enStreamMode", "stStreamAttribute", "szReserved");
	}
	/**
	 * @param ulChannelId \u901a\u9053ID<br>
	 * @param enStreamMode @see PU_STREAM_MODE_E<br>
	 * \u89c6\u9891\u6d41\u7c7b\u578b<br>
	 * C type : PU_STREAM_MODE_E<br>
	 * @param stStreamAttribute \u89c6\u9891\u5c5e\u6027<br>
	 * C type : PU_STREAM_ATTRIBUTE_S[PU_VIEDO_STREAM_FIVE]<br>
	 * @param szReserved szReserve[0]\u6807\u8bc6\u5168\u5e27\u7387  25:25HZ 30:30HZ 50\uff1a50HZ 60:60HZ<br>
	 * C type : CHAR[32]
	 */
	public PU_VIDEO_STREAM_INFO_V2(NativeLong ulChannelId, int enStreamMode, PU_STREAM_ATTRIBUTE stStreamAttribute[], byte szReserved[]) {
		super();
		this.ulChannelId = ulChannelId;
		this.enStreamMode = enStreamMode;
		if ((stStreamAttribute.length != this.stStreamAttribute.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.stStreamAttribute = stStreamAttribute;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public PU_VIDEO_STREAM_INFO_V2(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_VIDEO_STREAM_INFO_V2 implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_VIDEO_STREAM_INFO_V2 implements Structure.ByValue {
		
	};
}
