package com.burst.sdk.struct.hw;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_VW_BACKLIGHT_ADAPT_PARA extends Structure {
	/** \u901a\u9053\u53f7 */
	public NativeLong ulChannelID;
	/** \u80cc\u5149\u81ea\u9002\u5e94\u662f\u5426\u4f7f\u80fd */
	public boolean enBackLightAdaptEnable;
	/**
	 * \u80cc\u5149\u533a\u57df\u7c7b\u578b<br>
	 * C type : BACKLIGHT_MODE_E
	 */
	public int enBackLightMode;
	/**
	 * \u80cc\u5149\u81ea\u9002\u5e94\u533a\u57df\u4fe1\u606f<br>
	 * C type : PU_AREA_INFO_S
	 */
	public PU_AREA_INFO stBackLightAdaptStart;
	/** C type : CHAR[32] */
	public byte[] szReserved = new byte[32];
	public PU_VW_BACKLIGHT_ADAPT_PARA() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ulChannelID", "enBackLightAdaptEnable", "enBackLightMode", "stBackLightAdaptStart", "szReserved");
	}
	/**
	 * @param ulChannelID \u901a\u9053\u53f7<br>
	 * @param enBackLightAdaptEnable \u80cc\u5149\u81ea\u9002\u5e94\u662f\u5426\u4f7f\u80fd<br>
	 * @param enBackLightMode \u80cc\u5149\u533a\u57df\u7c7b\u578b<br>
	 * C type : BACKLIGHT_MODE_E<br>
	 * @param stBackLightAdaptStart \u80cc\u5149\u81ea\u9002\u5e94\u533a\u57df\u4fe1\u606f<br>
	 * C type : PU_AREA_INFO_S<br>
	 * @param szReserved C type : CHAR[32]
	 */
	public PU_VW_BACKLIGHT_ADAPT_PARA(NativeLong ulChannelID, boolean enBackLightAdaptEnable, int enBackLightMode, PU_AREA_INFO stBackLightAdaptStart, byte szReserved[]) {
		super();
		this.ulChannelID = ulChannelID;
		this.enBackLightAdaptEnable = enBackLightAdaptEnable;
		this.enBackLightMode = enBackLightMode;
		this.stBackLightAdaptStart = stBackLightAdaptStart;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public PU_VW_BACKLIGHT_ADAPT_PARA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_VW_BACKLIGHT_ADAPT_PARA implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_VW_BACKLIGHT_ADAPT_PARA implements Structure.ByValue {
		
	};
}
