package com.burst.sdk.struct.hw;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_VLPR_FTP_UPLOAD_PARA extends Structure {
	/** \u4f7f\u80fd */
	public boolean bSnapPicEnable;
	/** \u662f\u5426\u53d1\u9001\u8f66\u724c\u5c0f\u56fe */
	public boolean bSendPlatePic;
	/**
	 * \u4e0a\u4f20\u534f\u8bae<br>
	 * C type : PU_FTP_UPLOAD_PROTOCOL_TYPE_E
	 */
	public int enProtocol;
	/**
	 * \u670d\u52a1\u5668IP\u5730\u5740<br>
	 * C type : CHAR[16]
	 */
	public byte[] szServerIP = new byte[16];
	/** \u670d\u52a1\u5668\u7aef\u53e3 */
	public NativeLong ulServerPort;
	/**
	 * \u7528\u6237\u540d<br>
	 * C type : CHAR[(32 + 4)]
	 */
	public byte[] szUserName = new byte[32 + 4];
	/**
	 * \u76ee\u5f55\u547d\u540d\u53c2\u6570<br>
	 * C type : PU_VLPR_FTP_DIR_PARA_S
	 */
	public PU_VLPR_FTP_DIR_PARA_S stDirNameingPara;
	/**
	 * \u56fe\u7247\u547d\u540d\u53c2\u6570<br>
	 * C type : PU_PIC_NAMING_PARA_S
	 */
	public PU_PIC_NAMING_PARA stPicNamingPara;
	/** C type : PU_FTP_TYPE_E */
	public int eFtpType;
	/**
	 * \u9884\u7559\u5b57\u6bb5<br>
	 * C type : CHAR[32]
	 */
	public byte[] szReserved = new byte[32];
	/**
	 * Pwd<br>
	 * C type : CHAR[(64 + 4)]
	 */
	public byte[] szUserPwd = new byte[64 + 4];
	public PU_VLPR_FTP_UPLOAD_PARA() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("bSnapPicEnable", "bSendPlatePic", "enProtocol", "szServerIP", "ulServerPort", "szUserName", "stDirNameingPara", "stPicNamingPara", "eFtpType", "szReserved", "szUserPwd");
	}
	public PU_VLPR_FTP_UPLOAD_PARA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_VLPR_FTP_UPLOAD_PARA implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_VLPR_FTP_UPLOAD_PARA implements Structure.ByValue {
		
	};
}
