package com.burst.sdk.struct.hw;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_VIDEODIAGNOSIS_ENABLE_PARAM extends Structure {
	/** \u901a\u9053ID */
	public NativeLong ulChnID;
	/** \u7b97\u6cd5\u4f7f\u80fd */
	public boolean bEnable;
	/**
	 * \u6682\u65f6\u6ca1\u7528\uff0c\u5bf9\u5e94\u63a5\u53e3<br>
	 * C type : PU_ALARM_TIME_LIST_S
	 */
	public PU_ALARM_TIME_PARA_LIST stAlarmTimeList;
	public PU_VIDEODIAGNOSIS_ENABLE_PARAM() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ulChnID", "bEnable", "stAlarmTimeList");
	}
	/**
	 * @param ulChnID \u901a\u9053ID<br>
	 * @param bEnable \u7b97\u6cd5\u4f7f\u80fd<br>
	 * @param stAlarmTimeList \u6682\u65f6\u6ca1\u7528\uff0c\u5bf9\u5e94\u63a5\u53e3<br>
	 * C type : PU_ALARM_TIME_LIST_S
	 */
	public PU_VIDEODIAGNOSIS_ENABLE_PARAM(NativeLong ulChnID, boolean bEnable, PU_ALARM_TIME_PARA_LIST stAlarmTimeList) {
		super();
		this.ulChnID = ulChnID;
		this.bEnable = bEnable;
		this.stAlarmTimeList = stAlarmTimeList;
	}
	public PU_VIDEODIAGNOSIS_ENABLE_PARAM(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_VIDEODIAGNOSIS_ENABLE_PARAM implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_VIDEODIAGNOSIS_ENABLE_PARAM implements Structure.ByValue {
		
	};
}
