package com.burst.sdk.struct.hw;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_VW_OPERATE_3RD_APP extends Structure {
	/**
	 * @see PU_VW_OPERATE_3RD_APP_TYPE<br>
	 * C type : PU_VW_OPERATE_3RD_APP_TYPE
	 */
	public int enOperateType;
	/** C type : CHAR[32] */
	public byte[] szAppName = new byte[32];
	public PU_VW_OPERATE_3RD_APP() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("enOperateType", "szAppName");
	}
	/**
	 * @param enOperateType @see PU_VW_OPERATE_3RD_APP_TYPE<br>
	 * C type : PU_VW_OPERATE_3RD_APP_TYPE<br>
	 * @param szAppName C type : CHAR[32]
	 */
	public PU_VW_OPERATE_3RD_APP(int enOperateType, byte szAppName[]) {
		super();
		this.enOperateType = enOperateType;
		if ((szAppName.length != this.szAppName.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szAppName = szAppName;
	}
	public PU_VW_OPERATE_3RD_APP(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_VW_OPERATE_3RD_APP implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_VW_OPERATE_3RD_APP implements Structure.ByValue {
		
	};
}
