package com.burst.sdk.struct.hw;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class tagITSRunLightPara extends Structure {
	/**
	 * \u4f18\u5148\u7ea7\u522b<br>
	 * C type : PU_ITS_RUNLIGHT_PRIORITY_E
	 */
	public int enRunLightPriority;
	/**
	 * \u8fdd\u89c4\u903b\u8f91<br>
	 * C type : PU_ITS_RUNLIGHT_RULE_E
	 */
	public int enRunLightRule;
	/** \u7b2c\u4e8c\u5f20\u6293\u56fe\u504f\u79fb */
	public int iSecondSnapOffset;
	/** \u56fe\u7247\u6700\u5c0f\u504f\u79fb */
	public int iPicMinOffset;
	/** C type : CHAR[32] */
	public byte[] szReserve = new byte[32];
	public tagITSRunLightPara() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("enRunLightPriority", "enRunLightRule", "iSecondSnapOffset", "iPicMinOffset", "szReserve");
	}
	/**
	 * @param enRunLightPriority \u4f18\u5148\u7ea7\u522b<br>
	 * C type : PU_ITS_RUNLIGHT_PRIORITY_E<br>
	 * @param enRunLightRule \u8fdd\u89c4\u903b\u8f91<br>
	 * C type : PU_ITS_RUNLIGHT_RULE_E<br>
	 * @param iSecondSnapOffset \u7b2c\u4e8c\u5f20\u6293\u56fe\u504f\u79fb<br>
	 * @param iPicMinOffset \u56fe\u7247\u6700\u5c0f\u504f\u79fb<br>
	 * @param szReserve C type : CHAR[32]
	 */
	public tagITSRunLightPara(int enRunLightPriority, int enRunLightRule, int iSecondSnapOffset, int iPicMinOffset, byte szReserve[]) {
		super();
		this.enRunLightPriority = enRunLightPriority;
		this.enRunLightRule = enRunLightRule;
		this.iSecondSnapOffset = iSecondSnapOffset;
		this.iPicMinOffset = iPicMinOffset;
		if ((szReserve.length != this.szReserve.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserve = szReserve;
	}
	public tagITSRunLightPara(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends tagITSRunLightPara implements Structure.ByReference {
		
	};
	public static class ByValue extends tagITSRunLightPara implements Structure.ByValue {
		
	};
}
