package com.burst.sdk.struct.hw;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class tagRoadPropertyUnit extends Structure {
	/**
	 * \u8f66\u9053\u884c\u9a76\u65b9\u5411: \u6765\u5411\u53bb\u5411, \u5230\u753b\u9762\u4e2d\u662f\u5411\u4e0a\u5411\u4e0b<br>
	 * C type : PU_ITS_CAR_DRV_DIR_E
	 */
	public int enLaneDirection;
	/**
	 * \u6807\u5fd7\u8f66\u8f86\u884c\u9a76\u65b9\u5411: \u5de6\u53f3\u8f6c\u3001\u76f4\u884c\u7b49<br>
	 * C type : PU_ITS_ROAD_DRV_DIR_E
	 */
	public int enSignDirection;
	/**
	 * \u8f66\u9053\u7ebf\u7c7b\u578b<br>
	 * C type : ITS_ROAD_LINE_TYPE_E
	 */
	public int enLineType;
	/**
	 * \u8f66\u9053\u7ebf<br>
	 * C type : PU_IMRS_LINE_S
	 */
	public PU_IMRS_LINE stLine;
	public tagRoadPropertyUnit() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("enLaneDirection", "enSignDirection", "enLineType", "stLine");
	}
	/**
	 * @param enLaneDirection \u8f66\u9053\u884c\u9a76\u65b9\u5411: \u6765\u5411\u53bb\u5411, \u5230\u753b\u9762\u4e2d\u662f\u5411\u4e0a\u5411\u4e0b<br>
	 * C type : PU_ITS_CAR_DRV_DIR_E<br>
	 * @param enSignDirection \u6807\u5fd7\u8f66\u8f86\u884c\u9a76\u65b9\u5411: \u5de6\u53f3\u8f6c\u3001\u76f4\u884c\u7b49<br>
	 * C type : PU_ITS_ROAD_DRV_DIR_E<br>
	 * @param enLineType \u8f66\u9053\u7ebf\u7c7b\u578b<br>
	 * C type : ITS_ROAD_LINE_TYPE_E<br>
	 * @param stLine \u8f66\u9053\u7ebf<br>
	 * C type : PU_IMRS_LINE_S
	 */
	public tagRoadPropertyUnit(int enLaneDirection, int enSignDirection, int enLineType, PU_IMRS_LINE stLine) {
		super();
		this.enLaneDirection = enLaneDirection;
		this.enSignDirection = enSignDirection;
		this.enLineType = enLineType;
		this.stLine = stLine;
	}
	public tagRoadPropertyUnit(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends tagRoadPropertyUnit implements Structure.ByReference {
		
	};
	public static class ByValue extends tagRoadPropertyUnit implements Structure.ByValue {
		
	};
}
