package tunnel.sdk.struct.imos;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : sdk_struct.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class TagAreaScope extends Structure {
	/** C type : int */
	public int ulTopLeftX;
	/** C type : int */
	public int ulTopLeftY;
	/** C type : int */
	public int ulBottomRightX;
	/** C type : int */
	public int ulBottomRightY;
	public TagAreaScope() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ulTopLeftX", "ulTopLeftY", "ulBottomRightX", "ulBottomRightY");
	}
	/**
	 * @param ulTopLeftX C type : int<br>
	 * @param ulTopLeftY C type : int<br>
	 * @param ulBottomRightX C type : int<br>
	 * @param ulBottomRightY C type : int
	 */
	public TagAreaScope(int ulTopLeftX, int ulTopLeftY, int ulBottomRightX, int ulBottomRightY) {
		super();
		this.ulTopLeftX = ulTopLeftX;
		this.ulTopLeftY = ulTopLeftY;
		this.ulBottomRightX = ulBottomRightX;
		this.ulBottomRightY = ulBottomRightY;
	}
	public TagAreaScope(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends TagAreaScope implements Structure.ByReference {
		
	};
	public static class ByValue extends TagAreaScope implements Structure.ByValue {
		
	};
}
