package tunnel.sdk.struct.imos;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;
import static tunnel.sdk.constanst.IMOSDefLibrary.*;
/**
 * <i>native declaration : sdk_struct.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class TagCruisePlanBase extends Structure {
	/** C type : CHAR[IMOS_NAME_LEN] */
	public byte[] szCruisePlanName = new byte[IMOS_NAME_LEN];
	/** C type : CHAR[IMOS_NAME_LEN] */
	public byte[] szCreatorName = new byte[IMOS_NAME_LEN];
	/** C type : CHAR[IMOS_TIME_LEN] */
	public byte[] szCreatTime = new byte[IMOS_TIME_LEN];
	/** C type : CHAR[IMOS_RES_CODE_LEN] */
	public byte[] szCamCode = new byte[IMOS_RES_CODE_LEN];
	/** C type : CHAR[IMOS_NAME_LEN] */
	public byte[] szCamName = new byte[IMOS_NAME_LEN];
	/** C type : CHAR[IMOS_DOMAIN_CODE_LEN] */
	public byte[] szOrgCode = new byte[IMOS_DOMAIN_CODE_LEN];
	/** C type : int */
	public int ulPlanType;
	/** C type : CHAR[IMOS_DESC_LEN] */
	public byte[] szPlanDesc = new byte[IMOS_DESC_LEN];
	public TagCruisePlanBase() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("szCruisePlanName", "szCreatorName", "szCreatTime", "szCamCode", "szCamName", "szOrgCode", "ulPlanType", "szPlanDesc");
	}
	/**
	 * @param szCruisePlanName C type : CHAR[IMOS_NAME_LEN]<br>
	 * @param szCreatorName C type : CHAR[IMOS_NAME_LEN]<br>
	 * @param szCreatTime C type : CHAR[IMOS_TIME_LEN]<br>
	 * @param szCamCode C type : CHAR[IMOS_RES_CODE_LEN]<br>
	 * @param szCamName C type : CHAR[IMOS_NAME_LEN]<br>
	 * @param szOrgCode C type : CHAR[IMOS_DOMAIN_CODE_LEN]<br>
	 * @param ulPlanType C type : int<br>
	 * @param szPlanDesc C type : CHAR[IMOS_DESC_LEN]
	 */
	public TagCruisePlanBase(byte szCruisePlanName[], byte szCreatorName[], byte szCreatTime[], byte szCamCode[], byte szCamName[], byte szOrgCode[], int ulPlanType, byte szPlanDesc[]) {
		super();
		if ((szCruisePlanName.length != this.szCruisePlanName.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szCruisePlanName = szCruisePlanName;
		if ((szCreatorName.length != this.szCreatorName.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szCreatorName = szCreatorName;
		if ((szCreatTime.length != this.szCreatTime.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szCreatTime = szCreatTime;
		if ((szCamCode.length != this.szCamCode.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szCamCode = szCamCode;
		if ((szCamName.length != this.szCamName.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szCamName = szCamName;
		if ((szOrgCode.length != this.szOrgCode.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szOrgCode = szOrgCode;
		this.ulPlanType = ulPlanType;
		if ((szPlanDesc.length != this.szPlanDesc.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szPlanDesc = szPlanDesc;
	}
	public TagCruisePlanBase(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends TagCruisePlanBase implements Structure.ByReference {
		
	};
	public static class ByValue extends TagCruisePlanBase implements Structure.ByValue {
		
	};
}
