package tunnel.sdk.struct.imos;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;
import static tunnel.sdk.constanst.IMOSDefLibrary.*;
/**
 * <i>native declaration : sdk_struct.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class TagCDVResQueryItem extends Structure {
	/** C type : CHAR[IMOS_CODE_LEN] */
	public byte[] szCDVResCode = new byte[IMOS_CODE_LEN];
	/** C type : CHAR[IMOS_NAME_LEN] */
	public byte[] szCDVResName = new byte[IMOS_NAME_LEN];
	/** C type : CHAR[IMOS_NAME_LEN] */
	public byte[] szCDVName = new byte[IMOS_NAME_LEN];
	/** C type : CHAR[IMOS_NAME_LEN] */
	public byte[] szCDMName = new byte[IMOS_NAME_LEN];
	/** C type : int */
	public int ulCapacity;
	/** C type : int */
	public int ulCDVResStatus;
	/** C type : CHAR[32] */
	public byte[] szReserve = new byte[32];
	public TagCDVResQueryItem() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("szCDVResCode", "szCDVResName", "szCDVName", "szCDMName", "ulCapacity", "ulCDVResStatus", "szReserve");
	}
	/**
	 * @param szCDVResCode C type : CHAR[IMOS_CODE_LEN]<br>
	 * @param szCDVResName C type : CHAR[IMOS_NAME_LEN]<br>
	 * @param szCDVName C type : CHAR[IMOS_NAME_LEN]<br>
	 * @param szCDMName C type : CHAR[IMOS_NAME_LEN]<br>
	 * @param ulCapacity C type : int<br>
	 * @param ulCDVResStatus C type : int<br>
	 * @param szReserve C type : CHAR[32]
	 */
	public TagCDVResQueryItem(byte szCDVResCode[], byte szCDVResName[], byte szCDVName[], byte szCDMName[], int ulCapacity, int ulCDVResStatus, byte szReserve[]) {
		super();
		if ((szCDVResCode.length != this.szCDVResCode.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szCDVResCode = szCDVResCode;
		if ((szCDVResName.length != this.szCDVResName.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szCDVResName = szCDVResName;
		if ((szCDVName.length != this.szCDVName.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szCDVName = szCDVName;
		if ((szCDMName.length != this.szCDMName.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szCDMName = szCDMName;
		this.ulCapacity = ulCapacity;
		this.ulCDVResStatus = ulCDVResStatus;
		if ((szReserve.length != this.szReserve.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserve = szReserve;
	}
	public TagCDVResQueryItem(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends TagCDVResQueryItem implements Structure.ByReference {
		
	};
	public static class ByValue extends TagCDVResQueryItem implements Structure.ByValue {
		
	};
}
