package tunnel.sdk.struct.imos;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import static tunnel.sdk.constanst.IMOSDefLibrary.*;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : sdk_struct.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class TagIMOSBehaviorAnalyseInfo extends Structure {
	/** C type : int */
	public int bEnable;
	/** C type : IMOS_BEHAVIOR_ANALYSE_ARITHMETIC_S */
	public TagIMOSBehaviorAnalyseArithmetic stArithmetic;
	/** C type : IMOS_BEHAVIOR_ANALYSE_RULE_S[IMOS_BEHAVIOR_RULE_MAX] */
	public TagIMOSBehaviorAnalyseRule[] astRule = new TagIMOSBehaviorAnalyseRule[IMOS_BEHAVIOR_RULE_MAX];
	/** C type : CHAR[128] */
	public byte[] szReserve = new byte[128];
	public TagIMOSBehaviorAnalyseInfo() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("bEnable", "stArithmetic", "astRule", "szReserve");
	}
	/**
	 * @param bEnable C type : int<br>
	 * @param stArithmetic C type : IMOS_BEHAVIOR_ANALYSE_ARITHMETIC_S<br>
	 * @param astRule C type : IMOS_BEHAVIOR_ANALYSE_RULE_S[IMOS_BEHAVIOR_RULE_MAX]<br>
	 * @param szReserve C type : CHAR[128]
	 */
	public TagIMOSBehaviorAnalyseInfo(int bEnable, TagIMOSBehaviorAnalyseArithmetic stArithmetic, TagIMOSBehaviorAnalyseRule astRule[], byte szReserve[]) {
		super();
		this.bEnable = bEnable;
		this.stArithmetic = stArithmetic;
		if ((astRule.length != this.astRule.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.astRule = astRule;
		if ((szReserve.length != this.szReserve.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserve = szReserve;
	}
	public TagIMOSBehaviorAnalyseInfo(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends TagIMOSBehaviorAnalyseInfo implements Structure.ByReference {
		
	};
	public static class ByValue extends TagIMOSBehaviorAnalyseInfo implements Structure.ByValue {
		
	};
}
