package tunnel.sdk.struct.imos;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
import static tunnel.sdk.constanst.IMOSDefLibrary.*;
/**
 * <i>native declaration : sdk_struct.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class TagIPCAlarmSrcInfo extends Structure {
	/** C type : CHAR[IMOS_CODE_LEN] */
	public byte[] szAlarmSrcCode = new byte[IMOS_CODE_LEN];
	/** C type : CHAR[IMOS_NAME_LEN] */
	public byte[] szAlarmSrcName = new byte[IMOS_NAME_LEN];
	/** C type : CHAR[IMOS_CODE_LEN] */
	public byte[] szParentOrgCode = new byte[IMOS_CODE_LEN];
	public TagIPCAlarmSrcInfo() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("szAlarmSrcCode", "szAlarmSrcName", "szParentOrgCode");
	}
	/**
	 * @param szAlarmSrcCode C type : CHAR[IMOS_CODE_LEN]<br>
	 * @param szAlarmSrcName C type : CHAR[IMOS_NAME_LEN]<br>
	 * @param szParentOrgCode C type : CHAR[IMOS_CODE_LEN]
	 */
	public TagIPCAlarmSrcInfo(byte szAlarmSrcCode[], byte szAlarmSrcName[], byte szParentOrgCode[]) {
		super();
		if ((szAlarmSrcCode.length != this.szAlarmSrcCode.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szAlarmSrcCode = szAlarmSrcCode;
		if ((szAlarmSrcName.length != this.szAlarmSrcName.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szAlarmSrcName = szAlarmSrcName;
		if ((szParentOrgCode.length != this.szParentOrgCode.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szParentOrgCode = szParentOrgCode;
	}
	public TagIPCAlarmSrcInfo(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends TagIPCAlarmSrcInfo implements Structure.ByReference {
		
	};
	public static class ByValue extends TagIPCAlarmSrcInfo implements Structure.ByValue {
		
	};
}
