package tunnel.sdk.struct.imos;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : sdk_struct.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class TagIMOSBehaviorAnalyseArithmetic extends Structure {
	/** C type : int */
	public int ulFrameRate;
	/** C type : int */
	public int bShadow;
	/** C type : CHAR[128] */
	public byte[] szReserve = new byte[128];
	public TagIMOSBehaviorAnalyseArithmetic() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ulFrameRate", "bShadow", "szReserve");
	}
	/**
	 * @param ulFrameRate C type : int<br>
	 * @param bShadow C type : int<br>
	 * @param szReserve C type : CHAR[128]
	 */
	public TagIMOSBehaviorAnalyseArithmetic(int ulFrameRate, int bShadow, byte szReserve[]) {
		super();
		this.ulFrameRate = ulFrameRate;
		this.bShadow = bShadow;
		if ((szReserve.length != this.szReserve.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserve = szReserve;
	}
	public TagIMOSBehaviorAnalyseArithmetic(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends TagIMOSBehaviorAnalyseArithmetic implements Structure.ByReference {
		
	};
	public static class ByValue extends TagIMOSBehaviorAnalyseArithmetic implements Structure.ByValue {
		
	};
}
