package tunnel.sdk.struct.imos;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;
import static tunnel.sdk.constanst.IMOSDefLibrary.*;
/**
 * <i>native declaration : sdk_struct.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class TagOrgAuthority extends Structure {
	/** C type : AUTHORITY_ITEM_S[IMOS_AUTHORITY_MAX_NUM] */
	public TagAuthorityItem[] astAuthorities = new TagAuthorityItem[IMOS_AUTHORITY_MAX_NUM];
	/** C type : int */
	public int ulAuthCount;
	public TagOrgAuthority() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("astAuthorities", "ulAuthCount");
	}
	/**
	 * @param astAuthorities C type : AUTHORITY_ITEM_S[IMOS_AUTHORITY_MAX_NUM]<br>
	 * @param ulAuthCount C type : int
	 */
	public TagOrgAuthority(TagAuthorityItem astAuthorities[], int ulAuthCount) {
		super();
		if ((astAuthorities.length != this.astAuthorities.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.astAuthorities = astAuthorities;
		this.ulAuthCount = ulAuthCount;
	}
	public TagOrgAuthority(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends TagOrgAuthority implements Structure.ByReference {
		
	};
	public static class ByValue extends TagOrgAuthority implements Structure.ByValue {
		
	};
}
