package tunnel.sdk.struct.imos;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : sdk_struct.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class TagPTZParam extends Structure {
	/** C type : int */
	public int ulXMaxAngleSpeed;
	/** C type : int */
	public int ulYMaxAngleSpeed;
	/** C type : int */
	public int ulXMaxViewAngle;
	/** C type : int */
	public int ulYMaxViewAngle;
	/** C type : int */
	public int ulZoomTime;
	/** C type : int */
	public int ulZoomMultiple;
	public TagPTZParam() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ulXMaxAngleSpeed", "ulYMaxAngleSpeed", "ulXMaxViewAngle", "ulYMaxViewAngle", "ulZoomTime", "ulZoomMultiple");
	}
	/**
	 * @param ulXMaxAngleSpeed C type : int<br>
	 * @param ulYMaxAngleSpeed C type : int<br>
	 * @param ulXMaxViewAngle C type : int<br>
	 * @param ulYMaxViewAngle C type : int<br>
	 * @param ulZoomTime C type : int<br>
	 * @param ulZoomMultiple C type : int
	 */
	public TagPTZParam(int ulXMaxAngleSpeed, int ulYMaxAngleSpeed, int ulXMaxViewAngle, int ulYMaxViewAngle, int ulZoomTime, int ulZoomMultiple) {
		super();
		this.ulXMaxAngleSpeed = ulXMaxAngleSpeed;
		this.ulYMaxAngleSpeed = ulYMaxAngleSpeed;
		this.ulXMaxViewAngle = ulXMaxViewAngle;
		this.ulYMaxViewAngle = ulYMaxViewAngle;
		this.ulZoomTime = ulZoomTime;
		this.ulZoomMultiple = ulZoomMultiple;
	}
	public TagPTZParam(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends TagPTZParam implements Structure.ByReference {
		
	};
	public static class ByValue extends TagPTZParam implements Structure.ByValue {
		
	};
}
