package tunnel.sdk.struct.imos;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : sdk_struct.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class TagQueryPageInfo extends Structure {
	/** C type : int */
	public int ulPageRowNum;
	/** C type : int */
	public int ulPageFirstRowNumber;
	/** C type : int */
	public int bQueryCount;
	public TagQueryPageInfo() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ulPageRowNum", "ulPageFirstRowNumber", "bQueryCount");
	}
	/**
	 * @param ulPageRowNum C type : int<br>
	 * @param ulPageFirstRowNumber C type : int<br>
	 * @param bQueryCount C type : int 0:false 1:true
	 */
	public TagQueryPageInfo(int ulPageRowNum, int ulPageFirstRowNumber, int bQueryCount) {
		super();
		this.ulPageRowNum = ulPageRowNum;
		this.ulPageFirstRowNumber = ulPageFirstRowNumber;
		this.bQueryCount = bQueryCount;
	}
	public TagQueryPageInfo(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends TagQueryPageInfo implements Structure.ByReference {
	};
	public static class ByValue extends TagQueryPageInfo implements Structure.ByValue {
		
	};
}
