package tunnel.sdk.struct.imos;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
import static tunnel.sdk.constanst.IMOSDefLibrary.*;
/**
 * <i>native declaration : sdk_struct.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class TagQueryRoleConditionInfo extends Structure {
	/** C type : CHAR[IMOS_DOMAIN_CODE_LEN] */
	public byte[] szOrgCode = new byte[IMOS_DOMAIN_CODE_LEN];
	/** C type : CHAR[IMOS_NAME_LEN] */
	public byte[] szRoleName = new byte[IMOS_NAME_LEN];
	public TagQueryRoleConditionInfo() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("szOrgCode", "szRoleName");
	}
	/**
	 * @param szOrgCode C type : CHAR[IMOS_DOMAIN_CODE_LEN]<br>
	 * @param szRoleName C type : CHAR[IMOS_NAME_LEN]
	 */
	public TagQueryRoleConditionInfo(byte szOrgCode[], byte szRoleName[]) {
		super();
		if ((szOrgCode.length != this.szOrgCode.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szOrgCode = szOrgCode;
		if ((szRoleName.length != this.szRoleName.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szRoleName = szRoleName;
	}
	public TagQueryRoleConditionInfo(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends TagQueryRoleConditionInfo implements Structure.ByReference {
		
	};
	public static class ByValue extends TagQueryRoleConditionInfo implements Structure.ByValue {
		
	};
}
