package tunnel.sdk.struct.imos;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;
import static tunnel.sdk.constanst.IMOSDefLibrary.*;
/**
 * <i>native declaration : sdk_struct.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class TagSemaInputInfo extends Structure {
	/** C type : CHAR[IMOS_DESC_LEN] */
	public byte[] szSemaDesc = new byte[IMOS_DESC_LEN];
	/** C type : int */
	public int ulTriggerMode;
	/** C type : int */
	public int ulEnabledFlag;
	/** C type : int */
	public int ulEnableDetectFlag;
	public TagSemaInputInfo() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("szSemaDesc", "ulTriggerMode", "ulEnabledFlag", "ulEnableDetectFlag");
	}
	/**
	 * @param szSemaDesc C type : CHAR[IMOS_DESC_LEN]<br>
	 * @param ulTriggerMode C type : int<br>
	 * @param ulEnabledFlag C type : int<br>
	 * @param ulEnableDetectFlag C type : int
	 */
	public TagSemaInputInfo(byte szSemaDesc[], int ulTriggerMode, int ulEnabledFlag, int ulEnableDetectFlag) {
		super();
		if ((szSemaDesc.length != this.szSemaDesc.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szSemaDesc = szSemaDesc;
		this.ulTriggerMode = ulTriggerMode;
		this.ulEnabledFlag = ulEnabledFlag;
		this.ulEnableDetectFlag = ulEnableDetectFlag;
	}
	public TagSemaInputInfo(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends TagSemaInputInfo implements Structure.ByReference {
		
	};
	public static class ByValue extends TagSemaInputInfo implements Structure.ByValue {
		
	};
}
