package tunnel.sdk.struct.imos;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
import static tunnel.sdk.constanst.IMOSDefLibrary.*;
/**
 * <i>native declaration : sdk_struct.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class tagShareCameraBaseV2 extends Structure {
	/** C type : SHARE_CAMERA_BASE_S */
	public tagShareCameraBase stShareCamera;
	/** C type : CHAR[IMOS_DOMAIN_CODE_LEN] */
	public byte[] szParentOrgCode = new byte[IMOS_DOMAIN_CODE_LEN];
	public tagShareCameraBaseV2() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("stShareCamera", "szParentOrgCode");
	}
	/**
	 * @param stShareCamera C type : SHARE_CAMERA_BASE_S<br>
	 * @param szParentOrgCode C type : CHAR[IMOS_DOMAIN_CODE_LEN]
	 */
	public tagShareCameraBaseV2(tagShareCameraBase stShareCamera, byte szParentOrgCode[]) {
		super();
		this.stShareCamera = stShareCamera;
		if ((szParentOrgCode.length != this.szParentOrgCode.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szParentOrgCode = szParentOrgCode;
	}
	public tagShareCameraBaseV2(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends tagShareCameraBaseV2 implements Structure.ByReference {
		
	};
	public static class ByValue extends tagShareCameraBaseV2 implements Structure.ByValue {
		
	};
}
