package tunnel.sdk.struct.imos;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;
import static tunnel.sdk.constanst.IMOSDefLibrary.*;
/**
 * <i>native declaration : sdk_struct.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class tagUserRoleInfo extends Structure {
	/** C type : CHAR[IMOS_NAME_LEN] */
	public byte[] szRoleName = new byte[IMOS_NAME_LEN];
	/** C type : int */
	public int ulRolePriority;
	/** C type : CHAR[IMOS_DESC_LEN] */
	public byte[] szRoleDesc = new byte[IMOS_DESC_LEN];
	/** C type : CHAR[IMOS_DOMAIN_CODE_LEN] */
	public byte[] szOrgCode = new byte[IMOS_DOMAIN_CODE_LEN];
	/** C type : int */
	public int ulRoleType;
	/** C type : CHAR[IMOS_STRING_LEN_32] */
	public byte[] szExternInfo = new byte[IMOS_STRING_LEN_32];
	public tagUserRoleInfo() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("szRoleName", "ulRolePriority", "szRoleDesc", "szOrgCode", "ulRoleType", "szExternInfo");
	}
	/**
	 * @param szRoleName C type : CHAR[IMOS_NAME_LEN]<br>
	 * @param ulRolePriority C type : int<br>
	 * @param szRoleDesc C type : CHAR[IMOS_DESC_LEN]<br>
	 * @param szOrgCode C type : CHAR[IMOS_DOMAIN_CODE_LEN]<br>
	 * @param ulRoleType C type : int<br>
	 * @param szExternInfo C type : CHAR[IMOS_STRING_LEN_32]
	 */
	public tagUserRoleInfo(byte szRoleName[], int ulRolePriority, byte szRoleDesc[], byte szOrgCode[], int ulRoleType, byte szExternInfo[]) {
		super();
		if ((szRoleName.length != this.szRoleName.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szRoleName = szRoleName;
		this.ulRolePriority = ulRolePriority;
		if ((szRoleDesc.length != this.szRoleDesc.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szRoleDesc = szRoleDesc;
		if ((szOrgCode.length != this.szOrgCode.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szOrgCode = szOrgCode;
		this.ulRoleType = ulRoleType;
		if ((szExternInfo.length != this.szExternInfo.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szExternInfo = szExternInfo;
	}
	public tagUserRoleInfo(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends tagUserRoleInfo implements Structure.ByReference {
		
	};
	public static class ByValue extends tagUserRoleInfo implements Structure.ByValue {
		
	};
}
