package tunnel.sdk.struct.imos;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;
import static tunnel.sdk.constanst.IMOSDefLibrary.*;
/**
 * <i>native declaration : sdk_struct.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class tagVideoInChannel extends Structure {
	/** C type : CHAR[IMOS_DESC_LEN] */
	public byte[] szVinChannelDesc = new byte[IMOS_DESC_LEN];
	/** C type : CHAR[IMOS_IPADDR_LEN] */
	public byte[] szMulticastAddr = new byte[IMOS_IPADDR_LEN];
	/** C type : int */
	public int ulMulticastPort;
	/** C type : int */
	public int ulIsAutofit;
	/** C type : int */
	public int ulUseMSNum;
	/** C type : CHAR[IMOS_MS_MAX_NUM_PER_CHANNEL][IMOS_DEVICE_CODE_LEN] */
	public byte[] aszMSCode = new byte[((IMOS_MS_MAX_NUM_PER_CHANNEL) * (IMOS_DEVICE_CODE_LEN))];
	/** C type : int */
	public int ulEnableKeepout;
	/** C type : int */
	public int ulEnableMotionDetect;
	/** C type : int */
	public int ulEnableVideoLost;
	/** C type : int */
	public int ulSerialIndex;
	/** C type : int */
	public int ulBrightness;
	/** C type : int */
	public int ulContrast;
	/** C type : int */
	public int ulSaturation;
	/** C type : int */
	public int ulTone;
	/** C type : int */
	public int ulAudioEnabled;
	/** C type : int */
	public int ulAudioCoding;
	/** C type : int */
	public int ulAudioTrack;
	/** C type : int */
	public int ulSamplingRate;
	/** C type : int */
	public int ulAudioCodeRate;
	/** C type : int */
	public int ulIncrement;
	public tagVideoInChannel() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("szVinChannelDesc", "szMulticastAddr", "ulMulticastPort", "ulIsAutofit", "ulUseMSNum", "aszMSCode", "ulEnableKeepout", "ulEnableMotionDetect", "ulEnableVideoLost", "ulSerialIndex", "ulBrightness", "ulContrast", "ulSaturation", "ulTone", "ulAudioEnabled", "ulAudioCoding", "ulAudioTrack", "ulSamplingRate", "ulAudioCodeRate", "ulIncrement");
	}
	public tagVideoInChannel(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends tagVideoInChannel implements Structure.ByReference {
		
	};
	public static class ByValue extends tagVideoInChannel implements Structure.ByValue {
		
	};
}
