package tunnel.sdk.struct.imos;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : sdk_struct.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class tagVinChnlFullVarietyElement extends Structure {
	/** C type : int */
	public int ulOSDNameNum;
	/** C type : OSD_NAME_S* */
	public TagOsdName.ByReference pstOSDName;
	/** C type : int */
	public int ulMaskAreaNum;
	/** C type : VIDEO_AREA_S* */
	public tagVideoArea.ByReference pstMaskArea;
	/** C type : int */
	public int ulVideoStreamNum;
	/** C type : VIDEO_STREAM_S* */
	public tagVideoStream.ByReference pstVideoStream;
	/** C type : int */
	public int ulCoverDetecAreaNum;
	/** C type : VIDEO_AREA_S* */
	public tagVideoArea.ByReference pstCoverDetecArea;
	/** C type : int */
	public int ulMotionDetecAreaNum;
	/** C type : VIDEO_AREA_S* */
	public tagVideoArea.ByReference pstMotionDetecArea;
	public tagVinChnlFullVarietyElement() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ulOSDNameNum", "pstOSDName", "ulMaskAreaNum", "pstMaskArea", "ulVideoStreamNum", "pstVideoStream", "ulCoverDetecAreaNum", "pstCoverDetecArea", "ulMotionDetecAreaNum", "pstMotionDetecArea");
	}
	public tagVinChnlFullVarietyElement(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends tagVinChnlFullVarietyElement implements Structure.ByReference {
		
	};
	public static class ByValue extends tagVinChnlFullVarietyElement implements Structure.ByValue {
		
	};
}
