package tunnel.sdk.struct.imos;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : sdk_struct.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class tagVinChnlBindCameraBase extends Structure {
	/** C type : DEV_CHANNEL_INDEX_S */
	public TagDevChannelIndex stECChannelIndex;
	/** C type : CAMERA_INFO_S */
	public TagSCameraInfo stCameraInfo;
	/** C type : VIN_CHANNEL_S */
	public tagVideoInChannel stVinChannel;
	/** C type : OSD_TIME_S */
	public TagOsdTime stOSDTime;
	/** C type : OPTICS_PARAM_S */
	public TagOpticsParam stOpticsParam;
	/** C type : LOCATE_INFO_S */
	public TagLocateInfo stLocateInfo;
	/** C type : SAFE_CAMERA_INFO_S */
	public TagSafeCameraInfo stSafeCameraInfo;
	public tagVinChnlBindCameraBase() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("stECChannelIndex", "stCameraInfo", "stVinChannel", "stOSDTime", "stOpticsParam", "stLocateInfo", "stSafeCameraInfo");
	}
	/**
	 * @param stECChannelIndex C type : DEV_CHANNEL_INDEX_S<br>
	 * @param stCameraInfo C type : CAMERA_INFO_S<br>
	 * @param stVinChannel C type : VIN_CHANNEL_S<br>
	 * @param stOSDTime C type : OSD_TIME_S<br>
	 * @param stOpticsParam C type : OPTICS_PARAM_S<br>
	 * @param stLocateInfo C type : LOCATE_INFO_S<br>
	 * @param stSafeCameraInfo C type : SAFE_CAMERA_INFO_S
	 */
	public tagVinChnlBindCameraBase(TagDevChannelIndex stECChannelIndex, TagSCameraInfo stCameraInfo, tagVideoInChannel stVinChannel, TagOsdTime stOSDTime, TagOpticsParam stOpticsParam, TagLocateInfo stLocateInfo, TagSafeCameraInfo stSafeCameraInfo) {
		super();
		this.stECChannelIndex = stECChannelIndex;
		this.stCameraInfo = stCameraInfo;
		this.stVinChannel = stVinChannel;
		this.stOSDTime = stOSDTime;
		this.stOpticsParam = stOpticsParam;
		this.stLocateInfo = stLocateInfo;
		this.stSafeCameraInfo = stSafeCameraInfo;
	}
	public tagVinChnlBindCameraBase(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends tagVinChnlBindCameraBase implements Structure.ByReference {
		
	};
	public static class ByValue extends tagVinChnlBindCameraBase implements Structure.ByValue {
		
	};
}
