package tunnel.sdk.struct.hw;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CAM_FOCUSCTRL extends Structure {
	/** \u901a\u9053ID */
	public NativeLong ulChannelId;
	/** C type : PU_CAMCTRL_E */
	public int enFocus;
	/** \u7d22\u5c3c0~7\u9636\uff0c\u65e5\u7acb31\u9636 */
	public NativeLong ulFocusSpeed;
	/** C type : CHAR[32] */
	public byte[] szReserved = new byte[32];
	public CAM_FOCUSCTRL() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ulChannelId", "enFocus", "ulFocusSpeed", "szReserved");
	}
	/**
	 * @param ulChannelId \u901a\u9053ID<br>
	 * @param enFocus C type : PU_CAMCTRL_E<br>
	 * @param ulFocusSpeed \u7d22\u5c3c0~7\u9636\uff0c\u65e5\u7acb31\u9636<br>
	 * @param szReserved C type : CHAR[32]
	 */
	public CAM_FOCUSCTRL(NativeLong ulChannelId, int enFocus, NativeLong ulFocusSpeed, byte szReserved[]) {
		super();
		this.ulChannelId = ulChannelId;
		this.enFocus = enFocus;
		this.ulFocusSpeed = ulFocusSpeed;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public CAM_FOCUSCTRL(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends CAM_FOCUSCTRL implements Structure.ByReference {
		
	};
	public static class ByValue extends CAM_FOCUSCTRL implements Structure.ByValue {
		
	};
}
