package tunnel.sdk.struct.hw;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class META_RECT_S extends Structure {
	/** \u77e9\u5f62\u5de6\u4e0a\u9876\u70b9\u7684x\u5750\u6807 */
	public short usX;
	/** \u77e9\u5f62\u5de6\u4e0a\u9876\u70b9\u7684y\u5750\u6807 */
	public short usY;
	/** \u77e9\u5f62\u5bbd */
	public short usWidth;
	/** \u77e9\u5f62\u9ad8 */
	public short usHeight;
	public META_RECT_S() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("usX", "usY", "usWidth", "usHeight");
	}
	/**
	 * @param usX \u77e9\u5f62\u5de6\u4e0a\u9876\u70b9\u7684x\u5750\u6807<br>
	 * @param usY \u77e9\u5f62\u5de6\u4e0a\u9876\u70b9\u7684y\u5750\u6807<br>
	 * @param usWidth \u77e9\u5f62\u5bbd<br>
	 * @param usHeight \u77e9\u5f62\u9ad8
	 */
	public META_RECT_S(short usX, short usY, short usWidth, short usHeight) {
		super();
		this.usX = usX;
		this.usY = usY;
		this.usWidth = usWidth;
		this.usHeight = usHeight;
	}
	public META_RECT_S(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends META_RECT_S implements Structure.ByReference {
		
	};
	public static class ByValue extends META_RECT_S implements Structure.ByValue {
		
	};
}
