package tunnel.sdk.struct.hw;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import tunnel.sdk.library.HWPuSDKLibrary;

import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_3RD_APP_BASIC_INFO extends Structure {
	/** C type : CHAR[32] */
	public byte[] szAppName = new byte[32];
	/** C type : CHAR[32] */
	public byte[] szVersion = new byte[32];
	/** C type : CHAR[64] */
	public byte[] szURL = new byte[64];
	/**
	 * @see HWPuSDKLibrary.PU_VW_3RD_APP_STATUS
	 * C type : PU_VW_3RD_APP_STATUS
	 */
	public int enAppStatus;
	/**
	 * @see PU_VW_3RD_APP_ACTION<br>
	 * C type : PU_VW_3RD_APP_ACTION
	 */
	public int enAction;
	/** C type : CHAR[32] */
	public byte[] szReserved = new byte[32];
	public PU_3RD_APP_BASIC_INFO() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("szAppName", "szVersion", "szURL", "enAppStatus", "enAction", "szReserved");
	}
	/**
	 * @param szAppName C type : CHAR[32]<br>
	 * @param szVersion C type : CHAR[32]<br>
	 * @param szURL C type : CHAR[64]<br>
	 * @param enAppStatus @see PU_VW_3RD_APP_STATUS<br>
	 * C type : PU_VW_3RD_APP_STATUS<br>
	 * @param enAction @see PU_VW_3RD_APP_ACTION<br>
	 * C type : PU_VW_3RD_APP_ACTION<br>
	 * @param szReserved C type : CHAR[32]
	 */
	public PU_3RD_APP_BASIC_INFO(byte szAppName[], byte szVersion[], byte szURL[], int enAppStatus, int enAction, byte szReserved[]) {
		super();
		if ((szAppName.length != this.szAppName.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szAppName = szAppName;
		if ((szVersion.length != this.szVersion.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szVersion = szVersion;
		if ((szURL.length != this.szURL.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szURL = szURL;
		this.enAppStatus = enAppStatus;
		this.enAction = enAction;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public PU_3RD_APP_BASIC_INFO(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_3RD_APP_BASIC_INFO implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_3RD_APP_BASIC_INFO implements Structure.ByValue {
		
	};
}
