package tunnel.sdk.struct.hw;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_BLACKWHITE_MODE extends Structure {
	/**
	 * \u89c6\u9891\u6a21\u5f0f<br>
	 * C type : PU_VIDEO_BLACKWHITE_MODE_E
	 */
	public int enBKMode;
	public PU_BLACKWHITE_MODE() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("enBKMode");
	}
	/**
	 * @param enBKMode \u89c6\u9891\u6a21\u5f0f<br>
	 * C type : PU_VIDEO_BLACKWHITE_MODE_E
	 */
	public PU_BLACKWHITE_MODE(int enBKMode) {
		super();
		this.enBKMode = enBKMode;
	}
	public PU_BLACKWHITE_MODE(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_BLACKWHITE_MODE implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_BLACKWHITE_MODE implements Structure.ByValue {
		
	};
}
