package tunnel.sdk.struct.hw;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_CERT_EXPIRE_PERIOD_PARA extends Structure {
	/** \u68c0\u6d4b\u5468\u671f(\u5f53\u524d\u4e0d\u652f\u6301\u914d\u7f6e) */
	public NativeLong ulCheckPeriod;
	/** \u63d0\u524d\u544a\u8b66\u5468\u671f */
	public NativeLong ulAdvancedAlarmPeriod;
	public PU_CERT_EXPIRE_PERIOD_PARA() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ulCheckPeriod", "ulAdvancedAlarmPeriod");
	}
	/**
	 * @param ulCheckPeriod \u68c0\u6d4b\u5468\u671f(\u5f53\u524d\u4e0d\u652f\u6301\u914d\u7f6e)<br>
	 * @param ulAdvancedAlarmPeriod \u63d0\u524d\u544a\u8b66\u5468\u671f
	 */
	public PU_CERT_EXPIRE_PERIOD_PARA(NativeLong ulCheckPeriod, NativeLong ulAdvancedAlarmPeriod) {
		super();
		this.ulCheckPeriod = ulCheckPeriod;
		this.ulAdvancedAlarmPeriod = ulAdvancedAlarmPeriod;
	}
	public PU_CERT_EXPIRE_PERIOD_PARA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_CERT_EXPIRE_PERIOD_PARA implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_CERT_EXPIRE_PERIOD_PARA implements Structure.ByValue {
		
	};
}
