package tunnel.sdk.struct.hw;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_CAM_EXPCOMP_PARA extends Structure {
	/**
	 * \u66dd\u5149\u8865\u507f(\u5173\u95ed\u3001\u6253\u5f00)<br>
	 * C type : PU_COMMONMODE_SWITCH_E
	 */
	public int enExpComp;
	/** \u7cfb\u6570 0~255 */
	public NativeLong lExpComp;
	/** C type : CHAR[32] */
	public byte[] szReserve = new byte[32];
	public PU_CAM_EXPCOMP_PARA() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("enExpComp", "lExpComp", "szReserve");
	}
	/**
	 * @param enExpComp \u66dd\u5149\u8865\u507f(\u5173\u95ed\u3001\u6253\u5f00)<br>
	 * C type : PU_COMMONMODE_SWITCH_E<br>
	 * @param lExpComp \u7cfb\u6570 0~255<br>
	 * @param szReserve C type : CHAR[32]
	 */
	public PU_CAM_EXPCOMP_PARA(int enExpComp, NativeLong lExpComp, byte szReserve[]) {
		super();
		this.enExpComp = enExpComp;
		this.lExpComp = lExpComp;
		if ((szReserve.length != this.szReserve.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserve = szReserve;
	}
	public PU_CAM_EXPCOMP_PARA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_CAM_EXPCOMP_PARA implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_CAM_EXPCOMP_PARA implements Structure.ByValue {
		
	};
}
