package tunnel.sdk.struct.hw;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_CAM_AE_RESPONSE_TIME extends Structure {
	public NativeLong lAEResponseTime;
	public PU_CAM_AE_RESPONSE_TIME() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("lAEResponseTime");
	}
	public PU_CAM_AE_RESPONSE_TIME(NativeLong lAEResponseTime) {
		super();
		this.lAEResponseTime = lAEResponseTime;
	}
	public PU_CAM_AE_RESPONSE_TIME(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_CAM_AE_RESPONSE_TIME implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_CAM_AE_RESPONSE_TIME implements Structure.ByValue {
		
	};
}
