package tunnel.sdk.struct.hw;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public abstract class PU_DAYLIGHT_SAVING_TIME extends Structure {
	/**
	 * \u590f\u4ee4\u65f6\u5b9e\u65bd\u65b9\u5f0f<br>
	 * C type : PU_DST_TYPE_E
	 */
	public int enDSTType;
	/** \u590f\u4ee4\u65f6\u4f7f\u80fd */
	public boolean bEnable;
	/**
	 * \u590f\u4ee4\u65f6\u65f6\u95f4\u504f\u79fb<br>
	 * C type : PU_DST_OFFSET_E
	 */
	public int enOffset;
	/**
	 * \u590f\u4ee4\u65f6\u8d77\u59cb\u65f6\u95f4<br>
	 * C type : PU_DST_DATE_S
	 */
	public PU_DST_DATE stDSTStartTime;
	/**
	 * \u590f\u4ee4\u65f6\u7ed3\u675f\u65f6\u95f4<br>
	 * C type : PU_DST_DATE_S
	 */
	public PU_DST_DATE stDSTEndTime;
	/**
	 * \u590f\u4ee4\u65f6\u65e5\u671f\u65b9\u5f0f\u65f6\u95f4\u504f\u79fb<br>
	 * C type : PU_DST_OFFSET_E
	 */
	public int enDateWayOffset;
	/** Conversion Error : sizeof(int) */
	public PU_DAYLIGHT_SAVING_TIME() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("enDSTType", "bEnable", "enOffset", "stDSTStartTime", "stDSTEndTime", "enDateWayOffset");
	}
	/**
	 * @param enDSTType \u590f\u4ee4\u65f6\u5b9e\u65bd\u65b9\u5f0f<br>
	 * C type : PU_DST_TYPE_E<br>
	 * @param bEnable \u590f\u4ee4\u65f6\u4f7f\u80fd<br>
	 * @param enOffset \u590f\u4ee4\u65f6\u65f6\u95f4\u504f\u79fb<br>
	 * C type : PU_DST_OFFSET_E<br>
	 * @param stDSTStartTime \u590f\u4ee4\u65f6\u8d77\u59cb\u65f6\u95f4<br>
	 * C type : PU_DST_DATE_S<br>
	 * @param stDSTEndTime \u590f\u4ee4\u65f6\u7ed3\u675f\u65f6\u95f4<br>
	 * C type : PU_DST_DATE_S<br>
	 * @param enDateWayOffset \u590f\u4ee4\u65f6\u65e5\u671f\u65b9\u5f0f\u65f6\u95f4\u504f\u79fb<br>
	 * C type : PU_DST_OFFSET_E
	 */
	public PU_DAYLIGHT_SAVING_TIME(int enDSTType, boolean bEnable, int enOffset, PU_DST_DATE stDSTStartTime, PU_DST_DATE stDSTEndTime, int enDateWayOffset) {
		super();
		this.enDSTType = enDSTType;
		this.bEnable = bEnable;
		this.enOffset = enOffset;
		this.stDSTStartTime = stDSTStartTime;
		this.stDSTEndTime = stDSTEndTime;
		this.enDateWayOffset = enDateWayOffset;
	}
	public PU_DAYLIGHT_SAVING_TIME(Pointer peer) {
		super(peer);
	}
	public static abstract class ByReference extends PU_DAYLIGHT_SAVING_TIME implements Structure.ByReference {
		
	};
	public static abstract class ByValue extends PU_DAYLIGHT_SAVING_TIME implements Structure.ByValue {
		
	};
}
