package tunnel.sdk.struct.hw;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_DEV_ALARM_INFO_REPORT extends Structure {
	/** \u8bbe\u5907\u767b\u5165ID */
	public NativeLong ulIdentifyID;
	/** \u544a\u8b66\u6a21\u5757ID */
	public NativeLong ulAlarmModID;
	/** \u662f\u5426\u5b8c\u597d, 1:\u5b8c\u597d\uff1b0:\u4e0d\u5b8c\u597d */
	public boolean IsIntact;
	/**
	 * \u544a\u8b66\u7ea7\u522b<br>
	 * C type : PU_ALARM_LEVEL_E
	 */
	public int enAlarmLevel;
	/**
	 * \u544a\u8b66\u7c7b\u578b<br>
	 * C type : PU_ALARM_TYPE_E
	 */
	public int enAlarmType;
	/**
	 * \u544a\u8b66\u53d1\u751f/\u6d88\u9664\u65f6\u95f4UTC \u65f6\u95f4<br>
	 * C type : PU_TIME_S
	 */
	public PU_TIME stTime;
	/**
	 * \u544a\u8b66\u53d1\u751f/\u6d88\u9664<br>
	 * C type : PU_ALARM_ACTION_E
	 */
	public int enAction;
	/** \u544a\u8b66\u5e8f\u5217\u53f7 */
	public NativeLong ulAlarmId;
	/**
	 * \u544a\u8b66\u63cf\u8ff0<br>
	 * C type : CHAR[64]
	 */
	public byte[] szAlarmDesc = new byte[64];
	/**
	 * \u544a\u8b66\u6e05\u9664\u63cf\u8ff0<br>
	 * C type : CHAR[64]
	 */
	public byte[] szAlarmCleanDesc = new byte[64];
	/** C type : CHAR[32] */
	public byte[] szReserve = new byte[32];
	public PU_DEV_ALARM_INFO_REPORT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ulIdentifyID", "ulAlarmModID", "IsIntact", "enAlarmLevel", "enAlarmType", "stTime", "enAction", "ulAlarmId", "szAlarmDesc", "szAlarmCleanDesc", "szReserve");
	}
	public PU_DEV_ALARM_INFO_REPORT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_DEV_ALARM_INFO_REPORT implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_DEV_ALARM_INFO_REPORT implements Structure.ByValue {
		
	};
}
