package tunnel.sdk.struct.hw;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_FACE_PROCESS_PARAM extends Structure {
	/** \u53d1\u9001\u4eba\u8138\u62a0\u56fe */
	public boolean bSendFaceImg;
	/** \u53d1\u9001\u5168\u666f\u56fe */
	public boolean bSendPanorama;
	/** \u56fe\u50cf\u6293\u62cd\u8d28\u91cf(1-10) */
	public NativeLong ulImgQuality;
	/**
	 * szReserved[0]\u8868\u793a\u4eba\u8138\u62a0\u56fe\u5f20\u6570\uff081-5\uff09\uff0c\u9ed8\u8ba4\u4e3a1<br>
	 * C type : CHAR[32]
	 */
	public byte[] szReserved = new byte[32];
	public PU_FACE_PROCESS_PARAM() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("bSendFaceImg", "bSendPanorama", "ulImgQuality", "szReserved");
	}
	/**
	 * @param bSendFaceImg \u53d1\u9001\u4eba\u8138\u62a0\u56fe<br>
	 * @param bSendPanorama \u53d1\u9001\u5168\u666f\u56fe<br>
	 * @param ulImgQuality \u56fe\u50cf\u6293\u62cd\u8d28\u91cf(1-10)<br>
	 * @param szReserved szReserved[0]\u8868\u793a\u4eba\u8138\u62a0\u56fe\u5f20\u6570\uff081-5\uff09\uff0c\u9ed8\u8ba4\u4e3a1<br>
	 * C type : CHAR[32]
	 */
	public PU_FACE_PROCESS_PARAM(boolean bSendFaceImg, boolean bSendPanorama, NativeLong ulImgQuality, byte szReserved[]) {
		super();
		this.bSendFaceImg = bSendFaceImg;
		this.bSendPanorama = bSendPanorama;
		this.ulImgQuality = ulImgQuality;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public PU_FACE_PROCESS_PARAM(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_FACE_PROCESS_PARAM implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_FACE_PROCESS_PARAM implements Structure.ByValue {
		
	};
}
