package tunnel.sdk.struct.hw;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_FACE_PIC_GET_S extends Structure {
	/** \u901a\u9053ID */
	public NativeLong ulChannelId;
	/**
	 * \u540d\u5355\u5e93<br>
	 * C type : PU_FACE_LIB_S
	 */
	public PU_FACE_LIB_S stFacelib;
	/** \u4eba\u8138ID */
	public NativeLong uFaceID;
	/**
	 * \u67e5\u8be2\u7ed3\u679c\u8def\u5f84 (SDK\u672c\u5730)<br>
	 * C type : CHAR[128 + 1]
	 */
	public byte[] szFindResultPath = new byte[128 + 1];
	/** C type : CHAR[32] */
	public byte[] szReserve = new byte[32];
	public PU_FACE_PIC_GET_S() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ulChannelId", "stFacelib", "uFaceID", "szFindResultPath", "szReserve");
	}
	/**
	 * @param ulChannelId \u901a\u9053ID<br>
	 * @param stFacelib \u540d\u5355\u5e93<br>
	 * C type : PU_FACE_LIB_S<br>
	 * @param uFaceID \u4eba\u8138ID<br>
	 * @param szFindResultPath \u67e5\u8be2\u7ed3\u679c\u8def\u5f84 (SDK\u672c\u5730)<br>
	 * C type : CHAR[128 + 1]<br>
	 * @param szReserve C type : CHAR[32]
	 */
	public PU_FACE_PIC_GET_S(NativeLong ulChannelId, PU_FACE_LIB_S stFacelib, NativeLong uFaceID, byte szFindResultPath[], byte szReserve[]) {
		super();
		this.ulChannelId = ulChannelId;
		this.stFacelib = stFacelib;
		this.uFaceID = uFaceID;
		if ((szFindResultPath.length != this.szFindResultPath.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szFindResultPath = szFindResultPath;
		if ((szReserve.length != this.szReserve.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserve = szReserve;
	}
	public PU_FACE_PIC_GET_S(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_FACE_PIC_GET_S implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_FACE_PIC_GET_S implements Structure.ByValue {
		
	};
}
