package tunnel.sdk.struct.hw;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_HIDE_ALARM_PARA extends Structure {
	/** \u89c6\u9891\u901a\u9053ID */
	public NativeLong ulChannel;
	/** \u544a\u8b66\u4f7f\u80fd */
	public NativeLong lEnable;
	/** \u544a\u8b66\u68c0\u6d4b\u65f6\u95f4\u95f4\u96941~255s\uff0c\u6bcfx\u79d2\u68c0\u6d4b\u4e00\u6b21\u662f\u5426\u5728\u544a\u8b66\u72b6\u6001 */
	public NativeLong ulDeteInterval;
	/** \u8fd0\u52a8\u68c0\u6d4b\u7075\u654f\u5ea61~5\uff0c\u6570\u5b57\u8d8a\u9ad8\u8d8a\u7075\u654f */
	public NativeLong ulSensitivity;
	/**
	 * \u544a\u8b66\u68c0\u6d4b\u533a\u57df<br>
	 * C type : PU_DETECTION_AREA_S
	 */
	public PU_DETECTION_AREA stDetectionArea;
	/**
	 * \u5e03\u9632\u65f6\u95f4\u5217\u8868<br>
	 * C type : PU_ALARM_TIME_LIST_S
	 */
	public PU_ALARM_TIME_PARA_LIST stAlarmTimeList;
	public PU_HIDE_ALARM_PARA() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ulChannel", "lEnable", "ulDeteInterval", "ulSensitivity", "stDetectionArea", "stAlarmTimeList");
	}
	/**
	 * @param ulChannel \u89c6\u9891\u901a\u9053ID<br>
	 * @param lEnable \u544a\u8b66\u4f7f\u80fd<br>
	 * @param ulDeteInterval \u544a\u8b66\u68c0\u6d4b\u65f6\u95f4\u95f4\u96941~255s\uff0c\u6bcfx\u79d2\u68c0\u6d4b\u4e00\u6b21\u662f\u5426\u5728\u544a\u8b66\u72b6\u6001<br>
	 * @param ulSensitivity \u8fd0\u52a8\u68c0\u6d4b\u7075\u654f\u5ea61~5\uff0c\u6570\u5b57\u8d8a\u9ad8\u8d8a\u7075\u654f<br>
	 * @param stDetectionArea \u544a\u8b66\u68c0\u6d4b\u533a\u57df<br>
	 * C type : PU_DETECTION_AREA_S<br>
	 * @param stAlarmTimeList \u5e03\u9632\u65f6\u95f4\u5217\u8868<br>
	 * C type : PU_ALARM_TIME_LIST_S
	 */
	public PU_HIDE_ALARM_PARA(NativeLong ulChannel, NativeLong lEnable, NativeLong ulDeteInterval, NativeLong ulSensitivity, PU_DETECTION_AREA stDetectionArea, PU_ALARM_TIME_PARA_LIST stAlarmTimeList) {
		super();
		this.ulChannel = ulChannel;
		this.lEnable = lEnable;
		this.ulDeteInterval = ulDeteInterval;
		this.ulSensitivity = ulSensitivity;
		this.stDetectionArea = stDetectionArea;
		this.stAlarmTimeList = stAlarmTimeList;
	}
	public PU_HIDE_ALARM_PARA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_HIDE_ALARM_PARA implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_HIDE_ALARM_PARA implements Structure.ByValue {
		
	};
}
