package tunnel.sdk.struct.hw;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_IRIS_EMENDATION extends Structure {
	/** \u901a\u9053ID */
	public NativeLong ulChannelId;
	/**
	 * \u8bed\u8a00\u7c7b\u578b<br>
	 * C type : PU_LANGUAGE_TYPE_E
	 */
	public int enLanguageType;
	/** C type : CHAR[32] */
	public byte[] szReserved = new byte[32];
	public PU_IRIS_EMENDATION() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ulChannelId", "enLanguageType", "szReserved");
	}
	/**
	 * @param ulChannelId \u901a\u9053ID<br>
	 * @param enLanguageType \u8bed\u8a00\u7c7b\u578b<br>
	 * C type : PU_LANGUAGE_TYPE_E<br>
	 * @param szReserved C type : CHAR[32]
	 */
	public PU_IRIS_EMENDATION(NativeLong ulChannelId, int enLanguageType, byte szReserved[]) {
		super();
		this.ulChannelId = ulChannelId;
		this.enLanguageType = enLanguageType;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public PU_IRIS_EMENDATION(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_IRIS_EMENDATION implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_IRIS_EMENDATION implements Structure.ByValue {
		
	};
}
