package tunnel.sdk.struct.hw;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_ITS_EPOLICE_SIGNAL_LIGHT_PARAM extends Structure {
	/** \u901a\u9053ID */
	public NativeLong ulChannelId;
	/**
	 * \u7ea2\u7eff\u706f\u68c0\u6d4b\u63a5\u5165\u65b9\u5f0f<br>
	 * C type : PU_ITS_LIGHT_DT_TYPE_S
	 */
	public int enLightDtType;
	/** \u4fe1\u53f7\u706f\u533a\u57df\u4e2a\u6570 */
	public int iSignalLightAreaNum;
	/**
	 * \u4fe1\u53f7\u706f\u53c2\u6570<br>
	 * C type : PU_ITS_SIGNAL_LIGHT_AREA_PARAM_S[4]
	 */
	public PU_ITS_SIGNAL_LIGHT_AREA_PARAM[] astSignalLightList = new PU_ITS_SIGNAL_LIGHT_AREA_PARAM[4];
	/** C type : CHAR[32] */
	public byte[] szReserve = new byte[32];
	public PU_ITS_EPOLICE_SIGNAL_LIGHT_PARAM() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ulChannelId", "enLightDtType", "iSignalLightAreaNum", "astSignalLightList", "szReserve");
	}
	/**
	 * @param ulChannelId \u901a\u9053ID<br>
	 * @param enLightDtType \u7ea2\u7eff\u706f\u68c0\u6d4b\u63a5\u5165\u65b9\u5f0f<br>
	 * C type : PU_ITS_LIGHT_DT_TYPE_S<br>
	 * @param iSignalLightAreaNum \u4fe1\u53f7\u706f\u533a\u57df\u4e2a\u6570<br>
	 * @param astSignalLightList \u4fe1\u53f7\u706f\u53c2\u6570<br>
	 * C type : PU_ITS_SIGNAL_LIGHT_AREA_PARAM_S[4]<br>
	 * @param szReserve C type : CHAR[32]
	 */
	public PU_ITS_EPOLICE_SIGNAL_LIGHT_PARAM(NativeLong ulChannelId, int enLightDtType, int iSignalLightAreaNum, PU_ITS_SIGNAL_LIGHT_AREA_PARAM astSignalLightList[], byte szReserve[]) {
		super();
		this.ulChannelId = ulChannelId;
		this.enLightDtType = enLightDtType;
		this.iSignalLightAreaNum = iSignalLightAreaNum;
		if ((astSignalLightList.length != this.astSignalLightList.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.astSignalLightList = astSignalLightList;
		if ((szReserve.length != this.szReserve.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserve = szReserve;
	}
	public PU_ITS_EPOLICE_SIGNAL_LIGHT_PARAM(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_ITS_EPOLICE_SIGNAL_LIGHT_PARAM implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_ITS_EPOLICE_SIGNAL_LIGHT_PARAM implements Structure.ByValue {
		
	};
}
