package tunnel.sdk.struct.hw;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_MEDIA_PLAY_INFO extends Structure {
	/** \u901a\u9053\u53f7 */
	public NativeLong ulChannelId;
	/**
	 * \u5b9e\u65f6\u6d4f\u89c8\u3001\u8bed\u97f3\u5bf9\u8bb2\u3001\u8bed\u97f3\u5e7f\u64ad\u3001\u5f55\u50cf\u4e0b\u8f7d<br>
	 * C type : PU_BUSINESS_TYPE_E
	 */
	public int enBusinessType;
	/**
	 * \u4e3b\u7801\u6d41\u3001\u5b50\u7801\u6d411\u3001\u5b50\u7801\u6d412<br>
	 * C type : PU_STREAM_TYPE_E
	 */
	public int enStreamType;
	/**
	 * TCP\u3001UDP\u3001\u7ec4\u64ad\u65b9\u5f0f<br>
	 * C type : PU_PROTOCOL_TYPE_E
	 */
	public int enProtocolType;
	/**
	 * ES\u3001PS\u3001TS<br>
	 * C type : PU_VIDEO_CODE_TYPE_E
	 */
	public int enTansmitType;
	/**
	 * \u89c6\u9891\u6d41\u3001\u97f3\u9891\u6d41\u3001\u590d\u5408\u6d41<br>
	 * C type : PU_VIDEO_TYPE_E
	 */
	public int enVideoType;
	/**
	 * \u8bf7\u6c42\u7aefIP<br>
	 * C type : CHAR[16]
	 */
	public byte[] szLocalIp = new byte[16];
	/**
	 * \u8bf7\u6c42\u7aef\u7684\u7aef\u53e3\u53f7<br>
	 * C type : PU_PORT_INFO_S
	 */
	public PU_PORT_INFO stLocalPortInfo;
	/** \u8fde\u63a5\u7c7b\u578b\uff0c0\u76f4\u8fde 1\u4e2d\u8f6c */
	public NativeLong ulLinkMode;
	/**
	 * \u52a0\u5bc6\u7c7b\u578b<br>
	 * C type : PU_MEDIA_CRYPTO_TYPE_E
	 */
	public int enMediaCryptoType;
	/**
	 * \u89c6\u9891\u5bc6\u94a5<br>
	 * C type : CHAR[44]
	 */
	public byte[] szVideoCrypto = new byte[44];
	/**
	 * \u97f3\u9891\u5bc6\u94a5<br>
	 * C type : CHAR[44]
	 */
	public byte[] szAudioCrypto = new byte[44];
	/**
	 * \u8bf7\u6c42\u9884\u5f55\u3001\u5f55\u50cf\u5f00\u59cb\u65f6\u95f4<br>
	 * C type : PU_TIME_S
	 */
	public PU_TIME stStartTime;
	/**
	 * \u8bf7\u6c42\u9884\u5f55\u3001\u5f55\u50cf\u7ed3\u675f\u65f6\u95f4<br>
	 * C type : PU_TIME_S
	 */
	public PU_TIME stEndTime;
	/**
	 * \u7528\u4e8eNAT\u7a7f\u8d8a\u7684Session<br>
	 * C type : CHAR[32]
	 */
	public byte[] szSessionIDForNAT = new byte[32];
	/**
	 * \u7528\u4e8eNAT\u7684\u4f1a\u8bddURL<br>
	 * C type : CHAR[256]
	 */
	public byte[] szSessionUrl = new byte[256];
	/**
	 * szReserved[0]\u8868\u793a\u662f\u5426\u4fdd\u6d3b 0:\u4fdd\u6d3b,1:\u4e0d\u4fdd\u6d3b<br>
	 * C type : CHAR[32]
	 */
	public byte[] szReserved = new byte[32];
	public PU_MEDIA_PLAY_INFO() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ulChannelId", "enBusinessType", "enStreamType", "enProtocolType", "enTansmitType", "enVideoType", "szLocalIp", "stLocalPortInfo", "ulLinkMode", "enMediaCryptoType", "szVideoCrypto", "szAudioCrypto", "stStartTime", "stEndTime", "szSessionIDForNAT", "szSessionUrl", "szReserved");
	}
	public PU_MEDIA_PLAY_INFO(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_MEDIA_PLAY_INFO implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_MEDIA_PLAY_INFO implements Structure.ByValue {
		
	};
}
