package tunnel.sdk.struct.hw;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import tunnel.sdk.library.HWPuSDKLibrary;

import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_MASK_AREA_PARA_V20 extends Structure {
	/** C type : PU_IGT_POINT_S[4] */
	public PU_IGT_POINT[] stAreaPara = new PU_IGT_POINT[4];
	public NativeLong ulColor;
	/** C type : UCHAR */
	public HWPuSDKLibrary.UCHAR ucAlpha;
	public NativeLong ulIndex;
	/** C type : CHAR[32] */
	public byte[] szReserve = new byte[32];
	public PU_MASK_AREA_PARA_V20() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("stAreaPara", "ulColor", "ucAlpha", "ulIndex", "szReserve");
	}
	/**
	 * @param stAreaPara C type : PU_IGT_POINT_S[4]<br>
	 * @param ucAlpha C type : UCHAR<br>
	 * @param szReserve C type : CHAR[32]
	 */
	public PU_MASK_AREA_PARA_V20(PU_IGT_POINT stAreaPara[], NativeLong ulColor, HWPuSDKLibrary.UCHAR ucAlpha, NativeLong ulIndex, byte szReserve[]) {
		super();
		if ((stAreaPara.length != this.stAreaPara.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.stAreaPara = stAreaPara;
		this.ulColor = ulColor;
		this.ucAlpha = ucAlpha;
		this.ulIndex = ulIndex;
		if ((szReserve.length != this.szReserve.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserve = szReserve;
	}
	public PU_MASK_AREA_PARA_V20(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_MASK_AREA_PARA_V20 implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_MASK_AREA_PARA_V20 implements Structure.ByValue {
		
	};
}
