package tunnel.sdk.struct.hw;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import tunnel.sdk.library.HWPuSDKLibrary.UCHAR;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_META_TLV extends Structure {
	public int iType;
	public int uLength;
	/** C type : UCHAR* */
	public UCHAR pValue;
	public PU_META_TLV() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("iType", "uLength", "pValue");
	}
	/** @param pValue C type : UCHAR* */
	public PU_META_TLV(int iType, int uLength, UCHAR pValue) {
		super();
		this.iType = iType;
		this.uLength = uLength;
		this.pValue = pValue;
	}
	public PU_META_TLV(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_META_TLV implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_META_TLV implements Structure.ByValue {
		
	};
}
