package tunnel.sdk.struct.hw;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_MANUL_DIALING extends Structure {
	/** C type : DIAL_CONNECT_E */
	public int enDialConnect;
	public PU_MANUL_DIALING() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("enDialConnect");
	}
	/** @param enDialConnect C type : DIAL_CONNECT_E */
	public PU_MANUL_DIALING(int enDialConnect) {
		super();
		this.enDialConnect = enDialConnect;
	}
	public PU_MANUL_DIALING(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_MANUL_DIALING implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_MANUL_DIALING implements Structure.ByValue {
		
	};
}
