package tunnel.sdk.struct.hw;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_PRIVACY_MASK_AREA_LIST extends Structure {
	public NativeLong ulChnID;
	public NativeLong ulTotalNum;
	public NativeLong ulBeginIndex;
	public NativeLong ulEndIndex;
	public boolean bEnable;
	/** C type : PU_MASK_AREA_PARA_V20_S[10] */
	public PU_MASK_AREA_PARA_V20[] stMaskPara = new PU_MASK_AREA_PARA_V20[10];
	/** C type : CHAR[32] */
	public byte[] szReserve = new byte[32];
	public PU_PRIVACY_MASK_AREA_LIST() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ulChnID", "ulTotalNum", "ulBeginIndex", "ulEndIndex", "bEnable", "stMaskPara", "szReserve");
	}
	/**
	 * @param stMaskPara C type : PU_MASK_AREA_PARA_V20_S[10]<br>
	 * @param szReserve C type : CHAR[32]
	 */
	public PU_PRIVACY_MASK_AREA_LIST(NativeLong ulChnID, NativeLong ulTotalNum, NativeLong ulBeginIndex, NativeLong ulEndIndex, boolean bEnable, PU_MASK_AREA_PARA_V20 stMaskPara[], byte szReserve[]) {
		super();
		this.ulChnID = ulChnID;
		this.ulTotalNum = ulTotalNum;
		this.ulBeginIndex = ulBeginIndex;
		this.ulEndIndex = ulEndIndex;
		this.bEnable = bEnable;
		if ((stMaskPara.length != this.stMaskPara.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.stMaskPara = stMaskPara;
		if ((szReserve.length != this.szReserve.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserve = szReserve;
	}
	public PU_PRIVACY_MASK_AREA_LIST(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_PRIVACY_MASK_AREA_LIST implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_PRIVACY_MASK_AREA_LIST implements Structure.ByValue {
		
	};
}
