package tunnel.sdk.struct.hw;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import tunnel.sdk.library.HWPuSDKLibrary;

import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_REAL_PLAY_INFO_V20 extends Structure {
	/** \u901a\u9053ID */
	public NativeLong ulChannelId;
	/**
	 * Windows\u7a97\u53e3\u53e5\u67c4<br>
	 * C type : HWND
	 */
	public HWPuSDKLibrary.HWND hPlayWnd;
	/**
	 * \u7801\u6d41\u7c7b\u578b:\u4e3b\u7801\u6d41\u3001\u5b50\u7801\u6d411\u3001\u5b50\u7801\u6d412<br>
	 * C type : PU_STREAM_TYPE_E
	 */
	public int enStreamType;
	/**
	 * \u6d41\u7c7b\u578b\uff1a\u89c6\u9891\u6d41\u3001\u97f3\u9891\u6d41\u3001\u590d\u5408\u6d41\u3001\u5f55\u50cf\u6d41\u3001\u5143\u6570\u636e\u6d41<br>
	 * C type : PU_VIDEO_TYPE_E
	 */
	public int enVideoType;
	/**
	 * \u4f20\u8f93\u534f\u8bae\u7c7b\u578b: 0:UDP 1:TCP 2:\u7ec4\u64ad<br>
	 * C type : PU_PROTOCOL_TYPE_E
	 */
	public int enProtocolType;
	/**
	 * \u56de\u8c03\u7c7b\u578b\uff1a0:RTP\u89e3\u5bc6 1:RTP\u4e0d\u89e3\u5bc6  2:Frame 3:YUV<br>
	 * C type : PU_MEDIA_CALLBACK_TYPE_E
	 */
	public int enMediaCallbackType;
	/**
	 * \u8bf7\u6c42\u7aefIP<br>
	 * C type : CHAR[40]
	 */
	public byte[] szLocalIp = new byte[40];
	/** \u662f\u5426\u4fdd\u6d3b */
	public boolean bKeepLive;
	/**
	 * \u8bf7\u6c42\u9884\u5f55\u3001\u5f55\u50cf\u5f00\u59cb\u65f6\u95f4<br>
	 * C type : PU_TIME_S
	 */
	public PU_TIME stStartTime;
	/**
	 * \u8bf7\u6c42\u9884\u5f55\u3001\u5f55\u50cf\u7ed3\u675f\u65f6\u95f4<br>
	 * C type : PU_TIME_S
	 */
	public PU_TIME stEndTime;
	/**
	 * \u667a\u80fd\u6570\u636e\u683c\u5f0f 0:XML\u683c\u5f0f 1:\u5143\u6570\u636e\u683c\u5f0f<br>
	 * C type : PU_IGT_DATA_TYPE_E
	 */
	public int enIGTDataType;
	/**
	 * \u7ec4\u64adIP(\u7ec4\u64ad\u6d41\u9700\u8981\u8be5\u53c2\u6570)<br>
	 * C type : CHAR[40]
	 */
	public byte[] szMulticastIP = new byte[40];
	/** \u7ec4\u64ad\u7aef\u53e3(\u7ec4\u64ad\u6d41\u9700\u8981\u8be5\u53c2\u6570) */
	public NativeLong ulMulticastPort;
	/** C type : CHAR[32] */
	public byte[] szReserved = new byte[32];
	public PU_REAL_PLAY_INFO_V20() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ulChannelId", "hPlayWnd", "enStreamType", "enVideoType", "enProtocolType", "enMediaCallbackType", "szLocalIp", "bKeepLive", "stStartTime", "stEndTime", "enIGTDataType", "szMulticastIP", "ulMulticastPort", "szReserved");
	}
	public PU_REAL_PLAY_INFO_V20(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_REAL_PLAY_INFO_V20 implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_REAL_PLAY_INFO_V20 implements Structure.ByValue {
		
	};
}
