package tunnel.sdk.struct.hw;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_SUPPLEMENT_LIGHT_LAMP_INFO extends Structure {
	public NativeLong ulOutputId;
	/** \u706f\u7ec4\u4eae\u5ea6\u63a7\u52361-100 */
	public NativeLong ulLampGroupLum;
	/** \u5f00\u542f\u8865\u5149\u706f\u753b\u9762\u4eae\u5ea6\u7075\u654f\u5ea60-2 */
	public NativeLong ulSensitivity;
	/** C type : PU_SUPPLEMENT_LIGHT_LAMP_IO_MODE_E */
	public int enIOMode;
	/** C type : PU_SUPPLEMENT_LIGHT_LAMP_CTRL_MODE_E */
	public int enControlMode;
	/** C type : PU_SUPPLEMENT_LIGHT_LAMP_GUARD_INFO_S */
	public PU_SUPPLEMENT_LIGHT_LAMP_GUARD_INFO stTimePlan;
	/** C type : CHAR[32] */
	public byte[] szReserved = new byte[32];
	public PU_SUPPLEMENT_LIGHT_LAMP_INFO() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ulOutputId", "ulLampGroupLum", "ulSensitivity", "enIOMode", "enControlMode", "stTimePlan", "szReserved");
	}
	/**
	 * @param ulLampGroupLum \u706f\u7ec4\u4eae\u5ea6\u63a7\u52361-100<br>
	 * @param ulSensitivity \u5f00\u542f\u8865\u5149\u706f\u753b\u9762\u4eae\u5ea6\u7075\u654f\u5ea60-2<br>
	 * @param enIOMode C type : PU_SUPPLEMENT_LIGHT_LAMP_IO_MODE_E<br>
	 * @param enControlMode C type : PU_SUPPLEMENT_LIGHT_LAMP_CTRL_MODE_E<br>
	 * @param stTimePlan C type : PU_SUPPLEMENT_LIGHT_LAMP_GUARD_INFO_S<br>
	 * @param szReserved C type : CHAR[32]
	 */
	public PU_SUPPLEMENT_LIGHT_LAMP_INFO(NativeLong ulOutputId, NativeLong ulLampGroupLum, NativeLong ulSensitivity, int enIOMode, int enControlMode, PU_SUPPLEMENT_LIGHT_LAMP_GUARD_INFO stTimePlan, byte szReserved[]) {
		super();
		this.ulOutputId = ulOutputId;
		this.ulLampGroupLum = ulLampGroupLum;
		this.ulSensitivity = ulSensitivity;
		this.enIOMode = enIOMode;
		this.enControlMode = enControlMode;
		this.stTimePlan = stTimePlan;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public PU_SUPPLEMENT_LIGHT_LAMP_INFO(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_SUPPLEMENT_LIGHT_LAMP_INFO implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_SUPPLEMENT_LIGHT_LAMP_INFO implements Structure.ByValue {
		
	};
}
