package tunnel.sdk.struct.hw;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_SNAPSHOT_SPACE extends Structure {
	/** \u6293\u62cd\u7a7a\u95f4\u5360\u767e\u5206\u6bd4(\u5c0f\u6570\u90e8\u5206(2\u4f4d\u6709\u6548,\u7cbe\u786e\u81f3\u767e\u5206\u4f4d,1\u8868\u793a0.01%)) */
	public NativeLong ulPercentDecimal;
	/** \u6293\u62cd\u7a7a\u95f4\u5360\u767e\u5206\u6bd4(\u6574\u6570\u90e8\u5206) */
	public NativeLong ulPercentInt;
	public PU_SNAPSHOT_SPACE() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ulPercentDecimal", "ulPercentInt");
	}
	/**
	 * @param ulPercentDecimal \u6293\u62cd\u7a7a\u95f4\u5360\u767e\u5206\u6bd4(\u5c0f\u6570\u90e8\u5206(2\u4f4d\u6709\u6548,\u7cbe\u786e\u81f3\u767e\u5206\u4f4d,1\u8868\u793a0.01%))<br>
	 * @param ulPercentInt \u6293\u62cd\u7a7a\u95f4\u5360\u767e\u5206\u6bd4(\u6574\u6570\u90e8\u5206)
	 */
	public PU_SNAPSHOT_SPACE(NativeLong ulPercentDecimal, NativeLong ulPercentInt) {
		super();
		this.ulPercentDecimal = ulPercentDecimal;
		this.ulPercentInt = ulPercentInt;
	}
	public PU_SNAPSHOT_SPACE(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_SNAPSHOT_SPACE implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_SNAPSHOT_SPACE implements Structure.ByValue {
		
	};
}
