package tunnel.sdk.struct.hw;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_SMS_WHITE_LISTS extends Structure {
	/** C type : PU_SMS_CMD_INFO_S[(8)] */
	public PU_SMS_CMD_INFO[] szSmsWhiteList = new PU_SMS_CMD_INFO[8];
	public PU_SMS_WHITE_LISTS() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("szSmsWhiteList");
	}
	/** @param szSmsWhiteList C type : PU_SMS_CMD_INFO_S[(8)] */
	public PU_SMS_WHITE_LISTS(PU_SMS_CMD_INFO szSmsWhiteList[]) {
		super();
		if ((szSmsWhiteList.length != this.szSmsWhiteList.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szSmsWhiteList = szSmsWhiteList;
	}
	public PU_SMS_WHITE_LISTS(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_SMS_WHITE_LISTS implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_SMS_WHITE_LISTS implements Structure.ByValue {
		
	};
}
