package tunnel.sdk.struct.hw;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_TYPICAL_SCENE_INFO extends Structure {
	/**
	 * \u5178\u578b\u573a\u666f\u7c7b\u578b<br>
	 * C type : PU_TYPICAL_SCENE_MODE_E
	 */
	public int enSceneMode;
	/**
	 * \u5178\u578b\u573a\u666f\u9910\u540d\u79f0\u540d\u79f0<br>
	 * C type : CHAR[(64 + 4)]
	 */
	public byte[] szName = new byte[64 + 4];
	/**
	 * \u63cf\u8ff0<br>
	 * C type : CHAR[128]
	 */
	public byte[] szDescribe = new byte[128];
	/** C type : CHAR[32] */
	public byte[] szReserved = new byte[32];
	public PU_TYPICAL_SCENE_INFO() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("enSceneMode", "szName", "szDescribe", "szReserved");
	}
	/**
	 * @param enSceneMode \u5178\u578b\u573a\u666f\u7c7b\u578b<br>
	 * C type : PU_TYPICAL_SCENE_MODE_E<br>
	 * @param szName \u5178\u578b\u573a\u666f\u9910\u540d\u79f0\u540d\u79f0<br>
	 * C type : CHAR[(64 + 4)]<br>
	 * @param szDescribe \u63cf\u8ff0<br>
	 * C type : CHAR[128]<br>
	 * @param szReserved C type : CHAR[32]
	 */
	public PU_TYPICAL_SCENE_INFO(int enSceneMode, byte szName[], byte szDescribe[], byte szReserved[]) {
		super();
		this.enSceneMode = enSceneMode;
		if ((szName.length != this.szName.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szName = szName;
		if ((szDescribe.length != this.szDescribe.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szDescribe = szDescribe;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public PU_TYPICAL_SCENE_INFO(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_TYPICAL_SCENE_INFO implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_TYPICAL_SCENE_INFO implements Structure.ByValue {
		
	};
}
