package tunnel.sdk.struct.hw;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_VLPR_PARA_V2 extends Structure {
	/** \u901a\u9053ID */
	public NativeLong ulChnID;
	/** \u662f\u5426\u4f7f\u80fd */
	public boolean bEnable;
	/** \u8f66\u9053\u6570\u91cf */
	public int iLaneNum;
	/**
	 * \u8f66\u9053\u7ebf = \u8f66\u9053\u6570+1<br>
	 * C type : PU_IMRS_LINE_S[((4) + 1)]
	 */
	public PU_IMRS_LINE[] stLane = new PU_IMRS_LINE[(4) + 1];
	/**
	 * \u8f66\u8f86\u65b9\u5411\uff0c\u9ed8\u8ba4\u8f66\u5934<br>
	 * C type : PU_VEHICLE_DIR_E
	 */
	public int enVehicleDir;
	/**
	 * \u6293\u62cd\u7c7b\u578b 0:\u673a\u52a8\u8f66 1:\u673a\u975e\u4eba<br>
	 * C type : PU_VLPR_CATCH_MODE_E
	 */
	public int enCatchMode;
	/**
	 * \u8f66\u724c\u53c2\u6570<br>
	 * C type : PU_VLP_PARA_S
	 */
	public PU_VLP_PARA stVLPParam;
	/** \u8f66\u8f86\u989c\u8272\u68c0\u6d4b\u542f\u7528 */
	public boolean bVColorDetection;
	/** \u8f66\u8f86\u7c7b\u578b\u68c0\u6d4b\u542f\u7528 */
	public boolean bVTypeDetection;
	/** \u662f\u5426\u53d1\u9001\u5168\u666f\u56fe */
	public boolean bSendPanoramaPic;
	/** \u662f\u5426\u53d1\u9001\u8f66\u724c\u5c0f\u56fe */
	public boolean bSendPlatePic;
	/**
	 * \u8f66\u724c\u7b97\u6cd5\u7c7b\u578b<br>
	 * C type : PU_VLPR_ALG_MODE_E
	 */
	public int enAlgMode;
	/** C type : CHAR[32] */
	public byte[] szReserved = new byte[32];
	public PU_VLPR_PARA_V2() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ulChnID", "bEnable", "iLaneNum", "stLane", "enVehicleDir", "enCatchMode", "stVLPParam", "bVColorDetection", "bVTypeDetection", "bSendPanoramaPic", "bSendPlatePic", "enAlgMode", "szReserved");
	}
	public PU_VLPR_PARA_V2(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_VLPR_PARA_V2 implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_VLPR_PARA_V2 implements Structure.ByValue {
		
	};
}
