package com.burst.sdk.struct.imos;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

import static com.burst.sdk.constanst.IMOSDefLibrary.*;

/**
 * <i>native declaration : sdk_struct.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class TagCamAndChannelQueryItemV2 extends Structure {
	/** C type : DEV_CHANNEL_INDEX_S */
	public TagDevChannelIndex stECChannelIndex;
	/** C type : CHAR[IMOS_RES_CODE_LEN] */
	public byte[] szCamCode = new byte[IMOS_RES_CODE_LEN];
	/** C type : CHAR[IMOS_NAME_LEN] */
	public byte[] szCamName = new byte[IMOS_NAME_LEN];
	/** C type : int */
	public int ulCamType;
	/** C type : CHAR[IMOS_STRING_LEN_32] */
	public byte[] szPtzProtocol = new byte[IMOS_STRING_LEN_32];
	/** C type : int */
	public int ulPtzAddrCode;
	/** C type : CHAR[IMOS_IPADDR_LEN] */
	public byte[] szMulticastAddr = new byte[IMOS_IPADDR_LEN];
	/** C type : int */
	public int ulMulticastPort;
	/** C type : CHAR[IMOS_IPADDR_LEN] */
	public byte[] szSecondMulticastAddr = new byte[IMOS_IPADDR_LEN];
	/** C type : int */
	public int ulSecondMulticastPort;
	/** C type : CHAR[512] */
	public byte[] szReserve = new byte[512];
	public TagCamAndChannelQueryItemV2() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("stECChannelIndex", "szCamCode", "szCamName", "ulCamType", "szPtzProtocol", "ulPtzAddrCode", "szMulticastAddr", "ulMulticastPort", "szSecondMulticastAddr", "ulSecondMulticastPort", "szReserve");
	}
	public TagCamAndChannelQueryItemV2(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends TagCamAndChannelQueryItemV2 implements Structure.ByReference {
		
	};
	public static class ByValue extends TagCamAndChannelQueryItemV2 implements Structure.ByValue {
		
	};
}
