package com.burst.sdk.struct.imos;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;
import static  com.burst.sdk.constanst.IMOSDefLibrary.*;
/**
 * <i>native declaration : sdk_struct.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class TagDCQueryItem extends Structure {
	/** C type : CHAR[IMOS_DEVICE_CODE_LEN] */
	public byte[] szDCCode = new byte[IMOS_DEVICE_CODE_LEN];
	/** C type : CHAR[IMOS_NAME_LEN] */
	public byte[] szDCName = new byte[IMOS_NAME_LEN];
	/** C type : int */
	public int ulDCType;
	/** C type : int */
	public int ulDevaddrtype;
	/** C type : CHAR[IMOS_IPADDR_LEN] */
	public byte[] szDevAddr = new byte[IMOS_IPADDR_LEN];
	/** C type : CHAR[IMOS_DOMAIN_CODE_LEN] */
	public byte[] szOrgCode = new byte[IMOS_DOMAIN_CODE_LEN];
	/** C type : int */
	public int ulIsOnline;
	/** C type : int */
	public int ulDevExtStatus;
	/** C type : int */
	public int ulIsMulticast;
	/** C type : int */
	public int ulEnableAlarm;
	/** C type : int */
	public int ulEncodeType;
	/** C type : int */
	public int ulStandard;
	/** C type : int */
	public int ulRegProtocol;
	/** C type : CHAR[28] */
	public byte[] szReserve = new byte[28];
	public TagDCQueryItem() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("szDCCode", "szDCName", "ulDCType", "ulDevaddrtype", "szDevAddr", "szOrgCode", "ulIsOnline", "ulDevExtStatus", "ulIsMulticast", "ulEnableAlarm", "ulEncodeType", "ulStandard", "ulRegProtocol", "szReserve");
	}
	public TagDCQueryItem(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends TagDCQueryItem implements Structure.ByReference {
		
	};
	public static class ByValue extends TagDCQueryItem implements Structure.ByValue {
		
	};
}
