package com.burst.sdk.struct.imos;
import com.burst.sdk.constanst.IMOSDefLibrary;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.burst.sdk.constanst.IMOSDefLibrary;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : sdk_struct.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class tagDmShareResQueryItem extends Structure {
	/** C type : CHAR[IMOS_CODE_LEN] */
	public byte[] szShareResCode = new byte[IMOSDefLibrary.IMOS_CODE_LEN];
	/** C type : CHAR[IMOS_NAME_LEN] */
	public byte[] szResName = new byte[IMOSDefLibrary.IMOS_NAME_LEN];
	/** C type : CHAR[IMOS_NAME_LEN] */
	public byte[] szStoreDevName = new byte[IMOSDefLibrary.IMOS_NAME_LEN];
	/** C type : CHAR[IMOS_NAME_LEN] */
	public byte[] szDMName = new byte[IMOSDefLibrary.IMOS_NAME_LEN];
	/** C type : int */
	public int ulCapacity;
	/** C type : int */
	public int ulResStatus;
	/** C type : CHAR[32] */
	public byte[] szReserve = new byte[32];
	public tagDmShareResQueryItem() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("szShareResCode", "szResName", "szStoreDevName", "szDMName", "ulCapacity", "ulResStatus", "szReserve");
	}
	/**
	 * @param szShareResCode C type : CHAR[IMOS_CODE_LEN]<br>
	 * @param szResName C type : CHAR[IMOS_NAME_LEN]<br>
	 * @param szStoreDevName C type : CHAR[IMOS_NAME_LEN]<br>
	 * @param szDMName C type : CHAR[IMOS_NAME_LEN]<br>
	 * @param ulCapacity C type : int<br>
	 * @param ulResStatus C type : int<br>
	 * @param szReserve C type : CHAR[32]
	 */
	public tagDmShareResQueryItem(byte szShareResCode[], byte szResName[], byte szStoreDevName[], byte szDMName[], int ulCapacity, int ulResStatus, byte szReserve[]) {
		super();
		if ((szShareResCode.length != this.szShareResCode.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szShareResCode = szShareResCode;
		if ((szResName.length != this.szResName.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szResName = szResName;
		if ((szStoreDevName.length != this.szStoreDevName.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szStoreDevName = szStoreDevName;
		if ((szDMName.length != this.szDMName.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szDMName = szDMName;
		this.ulCapacity = ulCapacity;
		this.ulResStatus = ulResStatus;
		if ((szReserve.length != this.szReserve.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserve = szReserve;
	}
	public tagDmShareResQueryItem(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends tagDmShareResQueryItem implements Structure.ByReference {
		
	};
	public static class ByValue extends tagDmShareResQueryItem implements Structure.ByValue {
		
	};
}
