package com.burst.sdk.struct.imos;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;

import static com.burst.sdk.constanst.IMOSDefLibrary.IMOS_DECODERTAG_LEN;
import static com.burst.sdk.constanst.IMOSDefLibrary.IMOS_URL_LEN;

/**
 * <i>native declaration : sdk_struct.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class TagExDomainV2 extends Structure {
	/** C type : EX_DOMAIN_S */
	public TagExDomain stExDomainInfo;
	/** C type : int */
	public int bNeedAuthorize;
	/** C type : AUTHORIZATION_INFO_S */
	public TagAuthorizationInfo stAuthorization;
	/** C type : CHAR[IMOS_DECODERTAG_LEN] */
	public byte[] szDecoderTag = new byte[IMOS_DECODERTAG_LEN];
	/** C type : int */
	public int ulCtrlMode;
	/** C type : CHAR[IMOS_URL_LEN] */
	public byte[] szDomainURL = new byte[IMOS_URL_LEN];
	/** C type : int */
	public int ulPlaybackAutofit;
	/** C type : int */
	public int ulVoicecommAutofit;
	/** C type : int */
	public int ulSafeDevAddrcode;
	/** C type : int */
	public int ulONVIFTransPackMode;
	/** C type : int */
	public int ulBkpLinkFlag;
	/** C type : int */
	public int ulCatalogType;
	/** C type : int */
	public int ulExdomainMaxBakNum;
	/** C type : CHAR[108] */
	public byte[] szReserve = new byte[108];
	public TagExDomainV2() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("stExDomainInfo", "bNeedAuthorize", "stAuthorization", "szDecoderTag", "ulCtrlMode", "szDomainURL", "ulPlaybackAutofit", "ulVoicecommAutofit", "ulSafeDevAddrcode", "ulONVIFTransPackMode", "ulBkpLinkFlag", "ulCatalogType", "ulExdomainMaxBakNum", "szReserve");
	}
	public TagExDomainV2(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends TagExDomainV2 implements Structure.ByReference {
		
	};
	public static class ByValue extends TagExDomainV2 implements Structure.ByValue {
		
	};
}
