package com.burst.sdk.struct.imos;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
import static  com.burst.sdk.constanst.IMOSDefLibrary.*;
/**
 * <i>native declaration : sdk_struct.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class TagOsdImageListItem extends Structure {
	/** C type : CHAR[IMOS_RES_CODE_LEN] */
	public byte[] szOsdImageCode = new byte[IMOS_RES_CODE_LEN];
	/** C type : CHAR[IMOS_NAME_LEN] */
	public byte[] szName = new byte[IMOS_NAME_LEN];
	public TagOsdImageListItem() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("szOsdImageCode", "szName");
	}
	/**
	 * @param szOsdImageCode C type : CHAR[IMOS_RES_CODE_LEN]<br>
	 * @param szName C type : CHAR[IMOS_NAME_LEN]
	 */
	public TagOsdImageListItem(byte szOsdImageCode[], byte szName[]) {
		super();
		if ((szOsdImageCode.length != this.szOsdImageCode.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szOsdImageCode = szOsdImageCode;
		if ((szName.length != this.szName.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szName = szName;
	}
	public TagOsdImageListItem(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends TagOsdImageListItem implements Structure.ByReference {
		
	};
	public static class ByValue extends TagOsdImageListItem implements Structure.ByValue {
		
	};
}
