package com.burst.sdk.struct.imos;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : sdk_struct.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class TagOsdTime extends Structure {
	/** C type : int */
	public int ulOsdTimeIndex;
	/** C type : int */
	public int ulEnableFlag;
	/** C type : int */
	public int ulOsdTimeFormat;
	/** C type : int */
	public int ulOsdDateFormat;
	/** C type : int */
	public int ulOsdColor;
	/** C type : int */
	public int ulTransparence;
	/** C type : AREA_SCOPE_S */
	public TagAreaScope stAreaScope;
	public TagOsdTime() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ulOsdTimeIndex", "ulEnableFlag", "ulOsdTimeFormat", "ulOsdDateFormat", "ulOsdColor", "ulTransparence", "stAreaScope");
	}
	/**
	 * @param ulOsdTimeIndex C type : int<br>
	 * @param ulEnableFlag C type : int<br>
	 * @param ulOsdTimeFormat C type : int<br>
	 * @param ulOsdDateFormat C type : int<br>
	 * @param ulOsdColor C type : int<br>
	 * @param ulTransparence C type : int<br>
	 * @param stAreaScope C type : AREA_SCOPE_S
	 */
	public TagOsdTime(int ulOsdTimeIndex, int ulEnableFlag, int ulOsdTimeFormat, int ulOsdDateFormat, int ulOsdColor, int ulTransparence, TagAreaScope stAreaScope) {
		super();
		this.ulOsdTimeIndex = ulOsdTimeIndex;
		this.ulEnableFlag = ulEnableFlag;
		this.ulOsdTimeFormat = ulOsdTimeFormat;
		this.ulOsdDateFormat = ulOsdDateFormat;
		this.ulOsdColor = ulOsdColor;
		this.ulTransparence = ulTransparence;
		this.stAreaScope = stAreaScope;
	}
	public TagOsdTime(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends TagOsdTime implements Structure.ByReference {
	};
	public static class ByValue extends TagOsdTime implements Structure.ByValue {
		
	};
}
