package com.burst.sdk.struct.imos;
import com.burst.sdk.constanst.IMOSDefLibrary;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : sdk_struct.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class tagPlanExtTimeV2 extends Structure {
	/** C type : int */
	public int ulDateIndex;
	/** C type : CHAR[IMOS_SIMPLE_DATE_LEN] */
	public byte[] szExtDate = new byte[IMOSDefLibrary.IMOS_SIMPLE_DATE_LEN];
	/** C type : int */
	public int ulTimeSliceNum;
	/** C type : TIME_SLICE_INFO_V2_S[IMOS_MAX_TIME_SLICE_NUM] */
	public tagTimeSliceInfoV2[] astTimeInfoV2 = new tagTimeSliceInfoV2[IMOSDefLibrary.IMOS_MAX_TIME_SLICE_NUM];
	public tagPlanExtTimeV2() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ulDateIndex", "szExtDate", "ulTimeSliceNum", "astTimeInfoV2");
	}
	/**
	 * @param ulDateIndex C type : int<br>
	 * @param szExtDate C type : CHAR[IMOS_SIMPLE_DATE_LEN]<br>
	 * @param ulTimeSliceNum C type : int<br>
	 * @param astTimeInfoV2 C type : TIME_SLICE_INFO_V2_S[IMOS_MAX_TIME_SLICE_NUM]
	 */
	public tagPlanExtTimeV2(int ulDateIndex, byte szExtDate[], int ulTimeSliceNum, tagTimeSliceInfoV2 astTimeInfoV2[]) {
		super();
		this.ulDateIndex = ulDateIndex;
		if ((szExtDate.length != this.szExtDate.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szExtDate = szExtDate;
		this.ulTimeSliceNum = ulTimeSliceNum;
		if ((astTimeInfoV2.length != this.astTimeInfoV2.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.astTimeInfoV2 = astTimeInfoV2;
	}
	public tagPlanExtTimeV2(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends tagPlanExtTimeV2 implements Structure.ByReference {
		
	};
	public static class ByValue extends tagPlanExtTimeV2 implements Structure.ByValue {
		
	};
}
