package com.burst.sdk.struct.imos;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;

import static com.burst.sdk.constanst.IMOSDefLibrary.*;

/**
 * <i>native declaration : sdk_struct.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class TagQueryByName extends Structure {
	/** C type : CHAR[IMOS_NAME_LEN] */
	public byte[] szName = new byte[IMOS_NAME_LEN];
	public TagQueryByName() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("szName");
	}
	/** @param szName C type : CHAR[IMOS_NAME_LEN] */
	public TagQueryByName(byte szName[]) {
		super();
		if ((szName.length != this.szName.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szName = szName;
	}
	public TagQueryByName(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends TagQueryByName implements Structure.ByReference {
		
	};
	public static class ByValue extends TagQueryByName implements Structure.ByValue {
		
	};
}
