package com.burst.sdk.struct.imos;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : sdk_struct.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class TagReviseParam extends Structure {
	/** C type : int */
	public int ulXTurnCoefficient;
	/** C type : int */
	public int ulYTurnCoefficient;
	/** C type : int */
	public int ulFocusCoefficient;
	public TagReviseParam() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ulXTurnCoefficient", "ulYTurnCoefficient", "ulFocusCoefficient");
	}
	/**
	 * @param ulXTurnCoefficient C type : int<br>
	 * @param ulYTurnCoefficient C type : int<br>
	 * @param ulFocusCoefficient C type : int
	 */
	public TagReviseParam(int ulXTurnCoefficient, int ulYTurnCoefficient, int ulFocusCoefficient) {
		super();
		this.ulXTurnCoefficient = ulXTurnCoefficient;
		this.ulYTurnCoefficient = ulYTurnCoefficient;
		this.ulFocusCoefficient = ulFocusCoefficient;
	}
	public TagReviseParam(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends TagReviseParam implements Structure.ByReference {
		
	};
	public static class ByValue extends TagReviseParam implements Structure.ByValue {
		
	};
}
