package com.burst.sdk.struct.imos;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : sdk_struct.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class tagStoragePlan extends Structure {
	/** C type : STORY_PLAN_BASE_S */
	public tagStorePlanBase stStorageBasicInfo;
	/** C type : PLAN_TIME_S */
	public TagPlanTime stStorageTimeInfo;
	public tagStoragePlan() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("stStorageBasicInfo", "stStorageTimeInfo");
	}
	/**
	 * @param stStorageBasicInfo C type : STORY_PLAN_BASE_S<br>
	 * @param stStorageTimeInfo C type : PLAN_TIME_S
	 */
	public tagStoragePlan(tagStorePlanBase stStorageBasicInfo, TagPlanTime stStorageTimeInfo) {
		super();
		this.stStorageBasicInfo = stStorageBasicInfo;
		this.stStorageTimeInfo = stStorageTimeInfo;
	}
	public tagStoragePlan(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends tagStoragePlan implements Structure.ByReference {
		
	};
	public static class ByValue extends tagStoragePlan implements Structure.ByValue {
		
	};
}
