package com.burst.sdk.struct.imos;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;

import static com.burst.sdk.constanst.IMOSDefLibrary.IMOS_CODE_LEN;
import static com.burst.sdk.constanst.IMOSDefLibrary.IMOS_NAME_LEN;

/**
 * <i>native declaration : sdk_struct.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class tagShareAlarmOutBase extends Structure {
	/** C type : CHAR[IMOS_CODE_LEN] */
	public byte[] szAlarmOutCode = new byte[IMOS_CODE_LEN];
	/** C type : CHAR[IMOS_NAME_LEN] */
	public byte[] szAlarmOutName = new byte[IMOS_NAME_LEN];
	/** C type : CHAR[IMOS_CODE_LEN] */
	public byte[] szParentOrgCode = new byte[IMOS_CODE_LEN];
	/** C type : CHAR[IMOS_CODE_LEN] */
	public byte[] szAlarmOutShareCode = new byte[IMOS_CODE_LEN];
	public tagShareAlarmOutBase() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("szAlarmOutCode", "szAlarmOutName", "szParentOrgCode", "szAlarmOutShareCode");
	}
	/**
	 * @param szAlarmOutCode C type : CHAR[IMOS_CODE_LEN]<br>
	 * @param szAlarmOutName C type : CHAR[IMOS_NAME_LEN]<br>
	 * @param szParentOrgCode C type : CHAR[IMOS_CODE_LEN]<br>
	 * @param szAlarmOutShareCode C type : CHAR[IMOS_CODE_LEN]
	 */
	public tagShareAlarmOutBase(byte szAlarmOutCode[], byte szAlarmOutName[], byte szParentOrgCode[], byte szAlarmOutShareCode[]) {
		super();
		if ((szAlarmOutCode.length != this.szAlarmOutCode.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szAlarmOutCode = szAlarmOutCode;
		if ((szAlarmOutName.length != this.szAlarmOutName.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szAlarmOutName = szAlarmOutName;
		if ((szParentOrgCode.length != this.szParentOrgCode.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szParentOrgCode = szParentOrgCode;
		if ((szAlarmOutShareCode.length != this.szAlarmOutShareCode.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szAlarmOutShareCode = szAlarmOutShareCode;
	}
	public tagShareAlarmOutBase(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends tagShareAlarmOutBase implements Structure.ByReference {
		
	};
	public static class ByValue extends tagShareAlarmOutBase implements Structure.ByValue {
		
	};
}
