package com.burst.sdk.struct.imos;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

import static com.burst.sdk.constanst.IMOSDefLibrary.IMOS_DESC_LEN;

/**
 * <i>native declaration : sdk_struct.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class TagSemaOutputInfoSdk extends Structure {
	/** C type : CHAR[IMOS_DESC_LEN] */
	public byte[] szSemaDesc = new byte[IMOS_DESC_LEN];
	/** C type : int */
	public int ulTriggerMode;
	public TagSemaOutputInfoSdk() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("szSemaDesc", "ulTriggerMode");
	}
	/**
	 * @param szSemaDesc C type : CHAR[IMOS_DESC_LEN]<br>
	 * @param ulTriggerMode C type : int
	 */
	public TagSemaOutputInfoSdk(byte szSemaDesc[], int ulTriggerMode) {
		super();
		if ((szSemaDesc.length != this.szSemaDesc.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szSemaDesc = szSemaDesc;
		this.ulTriggerMode = ulTriggerMode;
	}
	public TagSemaOutputInfoSdk(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends TagSemaOutputInfoSdk implements Structure.ByReference {
		
	};
	public static class ByValue extends TagSemaOutputInfoSdk implements Structure.ByValue {
		
	};
}
