package com.burst.sdk.struct.imos;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import static com.burst.sdk.constanst.IMOSDefLibrary.*;

import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : sdk_struct.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class tagShareCamInfo extends Structure {
	/** C type : SHARE_CAMERA_BASE_S */
	public tagShareCameraBase stShareCamBaseInfo;
	/** C type : int */
	public int ulDevStatus;
	/** C type : int */
	public int bIsLocalDev;
	/** C type : CHAR[IMOS_DOMAIN_CODE_LEN] */
	public byte[] szExDomainCode = new byte[IMOS_DOMAIN_CODE_LEN];
	/** C type : CHAR[IMOS_DEVICE_CODE_LEN] */
	public byte[] szECCode = new byte[IMOS_DEVICE_CODE_LEN];
	public tagShareCamInfo() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("stShareCamBaseInfo", "ulDevStatus", "bIsLocalDev", "szExDomainCode", "szECCode");
	}
	/**
	 * @param stShareCamBaseInfo C type : SHARE_CAMERA_BASE_S<br>
	 * @param ulDevStatus C type : int<br>
	 * @param bIsLocalDev C type : int<br>
	 * @param szExDomainCode C type : CHAR[IMOS_DOMAIN_CODE_LEN]<br>
	 * @param szECCode C type : CHAR[IMOS_DEVICE_CODE_LEN]
	 */
	public tagShareCamInfo(tagShareCameraBase stShareCamBaseInfo, int ulDevStatus, int bIsLocalDev, byte szExDomainCode[], byte szECCode[]) {
		super();
		this.stShareCamBaseInfo = stShareCamBaseInfo;
		this.ulDevStatus = ulDevStatus;
		this.bIsLocalDev = bIsLocalDev;
		if ((szExDomainCode.length != this.szExDomainCode.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szExDomainCode = szExDomainCode;
		if ((szECCode.length != this.szECCode.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szECCode = szECCode;
	}
	public tagShareCamInfo(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends tagShareCamInfo implements Structure.ByReference {
		
	};
	public static class ByValue extends tagShareCamInfo implements Structure.ByValue {
		
	};
}
