package com.burst.sdk.struct.imos;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : sdk_struct.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class tagSemaQueryItem extends Structure {
	/** C type : int */
	public int ulSemaIndex;
	/** C type : int */
	public int ulSemaType;
	/** C type : int */
	public int ulTriggerMode;
	/** C type : int */
	public int ulEnabledFlag;
	public tagSemaQueryItem() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ulSemaIndex", "ulSemaType", "ulTriggerMode", "ulEnabledFlag");
	}
	/**
	 * @param ulSemaIndex C type : int<br>
	 * @param ulSemaType C type : int<br>
	 * @param ulTriggerMode C type : int<br>
	 * @param ulEnabledFlag C type : int
	 */
	public tagSemaQueryItem(int ulSemaIndex, int ulSemaType, int ulTriggerMode, int ulEnabledFlag) {
		super();
		this.ulSemaIndex = ulSemaIndex;
		this.ulSemaType = ulSemaType;
		this.ulTriggerMode = ulTriggerMode;
		this.ulEnabledFlag = ulEnabledFlag;
	}
	public tagSemaQueryItem(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends tagSemaQueryItem implements Structure.ByReference {
		
	};
	public static class ByValue extends tagSemaQueryItem implements Structure.ByValue {
		
	};
}
