package com.burst.sdk.struct.imos;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;
import static com.burst.sdk.constanst.IMOSDefLibrary.*;
/**
 * <i>native declaration : sdk_struct.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class TagSemaOutputInfoV2 extends Structure {
	/** C type : SEMA_OUTPUT_INFO_S */
	public TagSemaOutputInfoSdk stBaseOutputInfo;
	/** C type : int */
	public int ulOutPutTime;
	/** C type : CHAR[IMOS_CODE_LEN] */
	public byte[] szSwitchToken = new byte[IMOS_CODE_LEN];
	/** C type : CHAR[128] */
	public byte[] szRetention = new byte[128];
	public TagSemaOutputInfoV2() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("stBaseOutputInfo", "ulOutPutTime", "szSwitchToken", "szRetention");
	}
	/**
	 * @param stBaseOutputInfo C type : SEMA_OUTPUT_INFO_S<br>
	 * @param ulOutPutTime C type : int<br>
	 * @param szSwitchToken C type : CHAR[IMOS_CODE_LEN]<br>
	 * @param szRetention C type : CHAR[128]
	 */
	public TagSemaOutputInfoV2(TagSemaOutputInfoSdk stBaseOutputInfo, int ulOutPutTime, byte szSwitchToken[], byte szRetention[]) {
		super();
		this.stBaseOutputInfo = stBaseOutputInfo;
		this.ulOutPutTime = ulOutPutTime;
		if ((szSwitchToken.length != this.szSwitchToken.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szSwitchToken = szSwitchToken;
		if ((szRetention.length != this.szRetention.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szRetention = szRetention;
	}
	public TagSemaOutputInfoV2(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends TagSemaOutputInfoV2 implements Structure.ByReference {
		
	};
	public static class ByValue extends TagSemaOutputInfoV2 implements Structure.ByValue {
		
	};
}
