package com.burst.sdk.struct.imos;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;

import static com.burst.sdk.constanst.IMOSDefLibrary.IMOS_TIME_LEN;

/**
 * <i>native declaration : sdk_struct.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class tagTimeSlice extends Structure {
	/** C type : CHAR[IMOS_TIME_LEN] */
	public byte[] szBeginTime = new byte[IMOS_TIME_LEN];
	/** C type : CHAR[IMOS_TIME_LEN] */
	public byte[] szEndTime = new byte[IMOS_TIME_LEN];
	public tagTimeSlice() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("szBeginTime", "szEndTime");
	}
	/**
	 * @param szBeginTime C type : CHAR[IMOS_TIME_LEN]<br>
	 * @param szEndTime C type : CHAR[IMOS_TIME_LEN]
	 */
	public tagTimeSlice(byte szBeginTime[], byte szEndTime[]) {
		super();
		if ((szBeginTime.length != this.szBeginTime.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szBeginTime = szBeginTime;
		if ((szEndTime.length != this.szEndTime.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szEndTime = szEndTime;
	}
	public tagTimeSlice(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends tagTimeSlice implements Structure.ByReference {
		
	};
	public static class ByValue extends tagTimeSlice implements Structure.ByValue {
		
	};
}
