package com.burst.sdk.struct.imos;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;
import static com.burst.sdk.constanst.IMOSDefLibrary.*;
/**
 * <i>native declaration : sdk_struct.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class tagTSRuleUAInfo extends Structure {
	/** C type : int */
	public int ulUAType;
	/** C type : CHAR[IMOS_CODE_LEN] */
	public byte[] szUACode = new byte[IMOS_CODE_LEN];
	/** C type : CHAR[IMOS_NAME_LEN] */
	public byte[] szUAName = new byte[IMOS_NAME_LEN];
	public tagTSRuleUAInfo() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ulUAType", "szUACode", "szUAName");
	}
	/**
	 * @param ulUAType C type : int<br>
	 * @param szUACode C type : CHAR[IMOS_CODE_LEN]<br>
	 * @param szUAName C type : CHAR[IMOS_NAME_LEN]
	 */
	public tagTSRuleUAInfo(int ulUAType, byte szUACode[], byte szUAName[]) {
		super();
		this.ulUAType = ulUAType;
		if ((szUACode.length != this.szUACode.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szUACode = szUACode;
		if ((szUAName.length != this.szUAName.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szUAName = szUAName;
	}
	public tagTSRuleUAInfo(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends tagTSRuleUAInfo implements Structure.ByReference {
		
	};
	public static class ByValue extends tagTSRuleUAInfo implements Structure.ByValue {
		
	};
}
