package com.burst.sdk.struct.imos;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;
import static com.burst.sdk.constanst.IMOSDefLibrary.*;
/**
 * <i>native declaration : sdk_struct.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class tagUserQueryItem extends Structure {
	/** C type : CHAR[IMOS_USER_CODE_LEN] */
	public byte[] szUserCode = new byte[IMOS_USER_CODE_LEN];
	/** C type : CHAR[IMOS_RES_CODE_LEN] */
	public byte[] szUserLoginCode = new byte[IMOS_RES_CODE_LEN];
	/** C type : CHAR[IMOS_NAME_LEN] */
	public byte[] szUserName = new byte[IMOS_NAME_LEN];
	/** C type : CHAR[IMOS_NAME_LEN] */
	public byte[] szUserFullName = new byte[IMOS_NAME_LEN];
	/** C type : CHAR[IMOS_NAME_LEN] */
	public byte[] szOrgName = new byte[IMOS_NAME_LEN];
	/** C type : CHAR[IMOS_PHONE_LEN] */
	public byte[] szTelePhone = new byte[IMOS_PHONE_LEN];
	/** C type : CHAR[IMOS_MOBILE_LEN] */
	public byte[] szMobilePhone = new byte[IMOS_MOBILE_LEN];
	/** C type : CHAR[IMOS_MAIL_LEN] */
	public byte[] szEmail = new byte[IMOS_MAIL_LEN];
	/** C type : int */
	public int ulUserLockFlag;
	/** C type : CHAR[IMOS_IPADDR_LEN] */
	public byte[] szUserAddr = new byte[IMOS_IPADDR_LEN];
	/** C type : CHAR[IMOS_STRING_LEN_32] */
	public byte[] szExternInfo = new byte[IMOS_STRING_LEN_32];
	/** C type : CHAR[IMOS_TIME_LEN] */
	public byte[] szUserLoginTime = new byte[IMOS_TIME_LEN];
	public tagUserQueryItem() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("szUserCode", "szUserLoginCode", "szUserName", "szUserFullName", "szOrgName", "szTelePhone", "szMobilePhone", "szEmail", "ulUserLockFlag", "szUserAddr", "szExternInfo", "szUserLoginTime");
	}
	public tagUserQueryItem(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends tagUserQueryItem implements Structure.ByReference {
		
	};
	public static class ByValue extends tagUserQueryItem implements Structure.ByValue {
		
	};
}
